# -*- coding: utf-8 -*-
"""Kaggle script #6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksjf69Vy34W-sTDJ1OYr-IRtihRE3kK5
"""

import os
import random
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score, recall_score, confusion_matrix
import kagglehub

warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 5
ROUNDS = 15
LOCAL_EPOCHS = 3
BATCH_SIZE = 32

# ---------------------------------------------------------
# 2. Data Loading
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('uciml/breast-cancer-wisconsin-data')
csv_path = os.path.join(dataset_path, 'data.csv')

df = pd.read_csv(csv_path)
print(f"Data loaded successfully. Shape: {df.shape}")

# ---------------------------------------------------------
# 3. Preprocessing (Retained from Original Script)
# ---------------------------------------------------------
# Drop unnecessary columns
df.drop(['Unnamed: 32', 'id'], axis=1, inplace=True, errors='ignore')

# Handle highly correlated features (threshold > 0.95)
corr_matrix = df.drop('diagnosis', axis=1).corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
df.drop(to_drop, axis=1, inplace=True)

# Separate features and target
X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

# Encode target (M=1, B=0)
lb = LabelEncoder()
y_encoded = lb.fit_transform(y)

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=SEED)

# Scale features
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

# ---------------------------------------------------------
# 4. Federated Learning Setup: Client Data Partitioning
# ---------------------------------------------------------
def stratified_client_split(X_data, y_data, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)

    pos_idx = np.where(y_data == 1)[0]
    neg_idx = np.where(y_data == 0)[0]

    rng.shuffle(pos_idx)
    rng.shuffle(neg_idx)

    pos_parts = np.array_split(pos_idx, num_clients)
    neg_parts = np.array_split(neg_idx, num_clients)

    clients = {}
    for cid in range(num_clients):
        idx = np.concatenate([pos_parts[cid], neg_parts[cid]])
        rng.shuffle(idx)
        clients[f"client_{cid+1}"] = (X_data[idx], y_data[idx])

    return clients

client_data = stratified_client_split(X_train_scaled, y_train, num_clients=NUM_CLIENTS)
print(f"Data successfully partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 5. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model(input_dim):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(units=30, activation='relu', input_shape=(input_dim,)),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(units=30, activation='relu'),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(units=1, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        layer_avg = np.zeros_like(layer_weights[0])
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# ---------------------------------------------------------
# 6. Federated Training Loop
# ---------------------------------------------------------
input_dimension = X_train_scaled.shape[1]
global_model = create_model(input_dimension)
global_weights = global_model.get_weights()

print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for client_name, (x_c, y_c) in client_data.items():
        tf.keras.backend.clear_session()
        local_model = create_model(input_dimension)
        local_model.set_weights(global_weights)

        local_model.fit(
            x_c, y_c,
            epochs=LOCAL_EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=0,
        )

        local_weights.append(local_model.get_weights())
        local_sizes.append(len(x_c))

    # Aggregate weights
    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    if rnd % 5 == 0 or rnd == 1:
        val_prob = global_model.predict(X_test_scaled, verbose=0).ravel()
        val_pred = (val_prob > 0.5).astype(int)
        acc = accuracy_score(y_test, val_pred)
        print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 7. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Evaluation:")
final_prob = global_model.predict(X_test_scaled, verbose=0).ravel()
final_pred = (final_prob > 0.5).astype(int)

print("\nClassification Report:")
print(classification_report(y_test, final_pred, digits=3))
print("Confusion Matrix:")
print(confusion_matrix(y_test, final_pred))

import os
import pandas as pd
import kagglehub

# Reloading data since the session hasn't been initialized
dataset_path = kagglehub.dataset_download('uciml/breast-cancer-wisconsin-data')
csv_path = os.path.join(dataset_path, 'data.csv')
df = pd.read_csv(csv_path)

# Statistical summary (Transposed)
print("Dataset Statistical Summary:")
display(df.describe().T)

# 10 Random samples
print("\n10 Random Samples from Dataset:")
display(df.sample(10))