# -*- coding: utf-8 -*-
"""Kaggle script #19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3HzsiqU3x3si10khKqPrFtTn-mP6MA4
"""

import os
import random
import warnings
import copy
import glob
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

NUM_CLIENTS = 4
ROUNDS = 15
LOCAL_EPOCHS = 3
BATCH_SIZE = 16

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------------------------------------------
# 2. Data Loading & Preprocessing
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('fedesoriano/hepatitis-c-dataset')

csv_files = glob.glob(os.path.join(dataset_path, '**', '*.csv'), recursive=True)
if not csv_files:
    raise FileNotFoundError("Could not locate the CSV file.")

df = pd.read_csv(csv_files[0])
print(f"Data loaded successfully. Initial Shape: {df.shape}")

# Drop index column if it exists (usually 'Unnamed: 0')
if 'Unnamed: 0' in df.columns:
    df.drop('Unnamed: 0', axis=1, inplace=True)

# Handle missing values (impute with median for numerical columns)
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if df[col].dtype == 'object':
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
            df[col].fillna(df[col].median(), inplace=True)

# The target column is usually 'Category' in this dataset
target_col = 'Category'
if target_col not in df.columns:
    # Fallback just in case
    target_col = df.columns[0]

# Encode categorical features (like 'Sex')
label_encoders = {}
X_df = df.drop(target_col, axis=1)
for column in X_df.select_dtypes(include=['object', 'category']).columns:
    le = LabelEncoder()
    X_df[column] = le.fit_transform(X_df[column].astype(str))
    label_encoders[column] = le

# Encode Target
target_le = LabelEncoder()
y = target_le.fit_transform(df[target_col].astype(str))
num_classes = len(target_le.classes_)

X = X_df.values

# Global Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED, stratify=y)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert test sets to PyTorch tensors
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

# ---------------------------------------------------------
# 3. Custom Dataset & Federated Client Splitting
# ---------------------------------------------------------
class TabularDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

def stratified_client_split(X_data, y_data, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    client_X = [[] for _ in range(num_clients)]
    client_y = [[] for _ in range(num_clients)]

    unique_classes = np.unique(y_data)
    for cls in unique_classes:
        cls_idx = np.where(y_data == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_X[i].extend(X_data[splits[i]])
            client_y[i].extend(y_data[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_y[i]))
        rng.shuffle(c_idx)
        cx = np.array(client_X[i])[c_idx]
        cy = np.array(client_y[i])[c_idx]

        dataset = TabularDataset(cx, cy)
        loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)
        client_datasets.append(loader)

    return client_datasets

client_dataloaders = stratified_client_split(X_train_scaled, y_train, NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
class TabularMLP(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(TabularMLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, num_classes)
        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x)
        return x

input_dimension = X_train_scaled.shape[1]
global_model = TabularMLP(input_dim=input_dimension, num_classes=num_classes).to(device)
loss_func = nn.CrossEntropyLoss()

def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_dataloaders):
        local_model = TabularMLP(input_dim=input_dimension, num_classes=num_classes).to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=1e-3)

        for epoch in range(LOCAL_EPOCHS):
            for xb, yb in client_loader:
                xb, yb = xb.to(device), yb.to(device)
                opt.zero_grad()
                output = local_model(xb)
                loss = loss_func(output, yb)
                loss.backward()
                opt.step()

        local_weights.append(copy.deepcopy(local_model.state_dict()))
        local_sizes.append(len(client_loader.dataset))

    # Aggregate weights
    new_global_weights = fedavg(local_weights, local_sizes)
    global_model.load_state_dict(new_global_weights)

    # Global Validation
    global_model.eval()
    with torch.no_grad():
        xb, yb = X_test_tensor.to(device), y_test_tensor.to(device)
        outputs = global_model(xb)
        _, preds = torch.max(outputs, 1)
        acc = accuracy_score(yb.cpu().numpy(), preds.cpu().numpy())

    if rnd % 2 == 0 or rnd == 1:
        print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
target_names = [str(cls) for cls in target_le.classes_]
print(classification_report(y_test_tensor.cpu().numpy(), preds.cpu().numpy(), target_names=target_names, digits=3))

import kagglehub
import pandas as pd
import os
import glob

# Reloading the dataset as requested
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('fedesoriano/hepatitis-c-dataset')
csv_files = glob.glob(os.path.join(dataset_path, '**', '*.csv'), recursive=True)
df = pd.read_csv(csv_files[0])

# Descriptive statistics (Transposed)
print("\n--- Descriptive Statistics ---")
display(df.describe().T)

# 10 Random Samples
print("\n--- 10 Random Samples ---")
display(df.sample(10))