# -*- coding: utf-8 -*-
"""Kaggle script #21

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1al5et6nF4NW4iexJIIIlEqT6MfG-IIme
"""

# -*- coding: utf-8 -*-
"""
Breast Cancer Detection (PyTorch CNN) — Federated Learning Baseline
Converted from centralized PyTorch experimentation to a FedAvg architecture.
Preserves the original author's custom 'TestModel' CNN.
Saliency maps, heavy EDA, and multiple model comparisons have been removed.
"""

import os
import random
import warnings
import copy
from pathlib import Path
import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import transforms as T
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

NUM_CLIENTS = 4
ROUNDS = 10
LOCAL_EPOCHS = 2
BATCH_SIZE = 8  # Kept small for memory stability with 324x324 images
IMG_SIZE = (324, 324) # Author's original transform size

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------------------------------------------
# 2. Data Paths & Preprocessing
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('aryashah2k/breast-ultrasound-images-dataset')
root_dir = os.path.join(dataset_path, 'Dataset_BUSI_with_GT')

path = Path(root_dir)
path_images = list(path.glob('**/*.png'))

# Author's logic: exclude mask images
images_paths = [str(path_image) for path_image in path_images if '_mask' not in str(path_image)]
print(f'Number of usable images: {len(images_paths)}')

labels_raw = [os.path.split(os.path.split(name)[0])[1] for name in images_paths]
classes = sorted(list(set(labels_raw)))
labels_dict = {label: i for i, label in enumerate(classes)}
labels = [labels_dict[label_key] for label_key in labels_raw]
num_classes = len(classes)

print(f"Classes: {classes}")

# Global Train/Test Split
X_train_paths, X_test_paths, y_train, y_test = train_test_split(
    images_paths, labels, test_size=0.15, shuffle=True, random_state=SEED, stratify=labels
)

# ---------------------------------------------------------
# 3. Custom Dataset & Federated Client Splitting
# ---------------------------------------------------------
class BreastCancerDataset(torch.utils.data.Dataset):
    """Author's Custom PyTorch Dataset"""
    def __init__(self, images: list, labels: list, transform=None):
        super().__init__()
        self.images = images
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, index):
        image = Image.open(self.images[index]).convert('RGB')
        if self.transform:
            image = self.transform(image)
        label = self.labels[index]
        return image, torch.tensor(label, dtype=torch.long)

# Author's basic transforms
transform_pipeline = T.Compose([
    T.Resize(IMG_SIZE),
    T.ToTensor()
])

test_dataset = BreastCancerDataset(images=X_test_paths, labels=y_test, transform=transform_pipeline)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

def stratified_client_split(paths, labels, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    paths = np.array(paths)
    labels = np.array(labels)

    client_paths = [[] for _ in range(num_clients)]
    client_labels = [[] for _ in range(num_clients)]

    unique_classes = np.unique(labels)
    for cls in unique_classes:
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_paths[i].extend(paths[splits[i]])
            client_labels[i].extend(labels[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_labels[i]))
        rng.shuffle(c_idx)
        cp = np.array(client_paths[i])[c_idx].tolist()
        cl = np.array(client_labels[i])[c_idx].tolist()

        c_dataset = BreastCancerDataset(images=cp, labels=cl, transform=transform_pipeline)
        c_loader = DataLoader(c_dataset, batch_size=BATCH_SIZE, shuffle=True)
        client_datasets.append(c_loader)

    return client_datasets

client_dataloaders = stratified_client_split(X_train_paths, y_train, NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
class TestModel(nn.Module):
    """Author's EXACT custom architecture"""
    def __init__(self):
        super(TestModel, self).__init__()
        # 3 input image channels, 6 output channels, 5x5 square convolution kernel
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.conv2 = nn.Conv2d(6, 24, 3)

        self.fc1 = nn.Linear(24 * 79 * 79, 2048)
        self.fc2 = nn.Linear(2048, 256)
        self.fc3 = nn.Linear(256, 64)
        self.fc4 = nn.Linear(64, num_classes) # Adapted to num_classes dynamically

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)

        # changing the shape to pass to the next flattened layer
        x = x.view(x.size(0), 24 * 79 * 79)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x

global_model = TestModel().to(device)
loss_func = nn.CrossEntropyLoss()

def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_dataloaders):
        local_model = TestModel().to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=1e-4) # Lowered LR slightly for FedAvg stability

        for epoch in range(LOCAL_EPOCHS):
            for xb, yb in client_loader:
                xb, yb = xb.to(device), yb.to(device)
                opt.zero_grad()
                output = local_model(xb)
                loss = loss_func(output, yb)
                loss.backward()
                opt.step()

        local_weights.append(copy.deepcopy(local_model.state_dict()))
        local_sizes.append(len(client_loader.dataset))

    # Aggregate weights
    new_global_weights = fedavg(local_weights, local_sizes)
    global_model.load_state_dict(new_global_weights)

    # Global Validation
    global_model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            outputs = global_model(xb)
            _, preds = torch.max(outputs, 1)

            y_true.extend(yb.numpy())
            y_pred.extend(preds.cpu().numpy())

    acc = accuracy_score(y_true, y_pred)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
print(classification_report(y_true, y_pred, target_names=classes, digits=3))