# -*- coding: utf-8 -*-
"""Kaggle Script #15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Z_8gDFhZoSeHFkEQY5YfiA_yfvo1jc5
"""

# -*- coding: utf-8 -*-
"""
Skin Cancer Detection (9 Classes) — Federated Learning Baseline
Converted from centralized TensorFlow/Keras to a TF FedAvg architecture.
Preserves the original author's 5-layer CNN with progressive Dropouts.
External 'Augmentor' disk-writing logic and Matplotlib EDA removed for FL stability.
Strict memory management implemented to prevent OOM crashes during FedAvg.
"""

import os
import gc
import random
import warnings
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout, Rescaling
from tensorflow.keras.optimizers import Adam
import kagglehub

warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 123 # Author's original seed
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 10
LOCAL_EPOCHS = 2
BATCH_SIZE = 16
IMG_SIZE = (180, 180) # Author's original dimension

# ---------------------------------------------------------
# 2. Data Paths & Preprocessing (Dynamic 9-Class Radar)
# ---------------------------------------------------------
print("Locating dataset...")
dataset_path = '/kaggle/input/skin-cancer9-classesisic'
if not os.path.exists(dataset_path):
    dataset_path = kagglehub.dataset_download('nodoubttome/skin-cancer9-classesisic')

image_paths = []
raw_labels = []

# Deep scan to bypass nested Train/Test folders and dynamically map classes
for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.jpeg', '.jpg', '.png')):
            full_path = os.path.join(root, file)
            class_name = os.path.basename(root)

            # Ignore structural folders if they accidentally contain images
            if class_name.lower() not in ['train', 'test']:
                image_paths.append(full_path)
                raw_labels.append(class_name)

if not image_paths:
    raise FileNotFoundError("Could not locate Skin Cancer images.")

# Dynamically encode the 9 classes
class_names = sorted(list(set(raw_labels)))
label_mapping = {name: i for i, name in enumerate(class_names)}
image_labels = [label_mapping[label] for label in raw_labels]

print(f"Total Images Found: {len(image_paths)}")
print(f"Detected Classes: {class_names}")

# Global Train/Test Split (Author used 0.2 split logic)
X_train_paths, X_test_paths, y_train, y_test = train_test_split(
    image_paths, image_labels, test_size=0.2, random_state=SEED, stratify=image_labels
)

# ---------------------------------------------------------
# 3. tf.data Pipeline & Federated Client Splitting
# ---------------------------------------------------------
def process_path(file_path, label):
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    # The author used a Rescaling layer inside the model, so we leave pixel values at 0-255 here.
    return img, label

def create_tf_dataset(paths, labels, batch_size, is_training=True):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if is_training:
        ds = ds.shuffle(len(paths), seed=SEED)
    ds = ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds

def stratified_client_split(paths, labels, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    paths = np.array(paths)
    labels = np.array(labels)

    client_paths = [[] for _ in range(num_clients)]
    client_labels = [[] for _ in range(num_clients)]

    unique_classes = np.unique(labels)
    for cls in unique_classes:
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_paths[i].extend(paths[splits[i]])
            client_labels[i].extend(labels[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_labels[i]))
        rng.shuffle(c_idx)
        cp = np.array(client_paths[i])[c_idx]
        cl = np.array(client_labels[i])[c_idx]

        # Limit subset size to prevent RAM overflow
        MAX_PER_CLIENT = 1500
        cp = cp[:MAX_PER_CLIENT]
        cl = cl[:MAX_PER_CLIENT]

        dataset = create_tf_dataset(cp, cl, BATCH_SIZE, is_training=True)
        client_datasets.append((dataset, len(cl)))

    return client_datasets

client_data_tuples = stratified_client_split(X_train_paths, y_train, NUM_CLIENTS)
test_dataset = create_tf_dataset(X_test_paths[:1000], y_test[:1000], BATCH_SIZE, is_training=False)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_keras_model():
    """Author's EXACT Custom 5-Layer CNN Architecture"""
    model = Sequential([
        Rescaling(1.0/255, input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
    ])

    model.add(Conv2D(32, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())

    model.add(Conv2D(64, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())

    model.add(Conv2D(128, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())
    model.add(Dropout(0.15))

    model.add(Conv2D(256, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())
    model.add(Dropout(0.20))

    model.add(Conv2D(512, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(1024, activation="relu"))

    # 9 classes
    model.add(Dense(units=len(class_names), activation='softmax'))

    # Original author used sparse categorical with from_logits=True while having a softmax.
    # To keep their mathematical setup exactly the same, we preserve their loss configuration.
    opt = Adam(learning_rate=0.001)
    model.compile(optimizer=opt, loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
    return model

_temp_model = create_keras_model()
global_weights = _temp_model.get_weights()
del _temp_model
tf.keras.backend.clear_session()

def fedavg_tf(weights_list, sizes):
    total_size = sum(sizes)
    avg_weights = []
    for weights_layer_tuple in zip(*weights_list):
        layer_mean = sum(w * (s / total_size) for w, s in zip(weights_layer_tuple, sizes))
        avg_weights.append(layer_mean)
    return avg_weights

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for c_idx, (client_dataset, c_size) in enumerate(client_data_tuples):
        local_model = create_keras_model()
        local_model.set_weights(global_weights)

        local_model.fit(client_dataset, epochs=LOCAL_EPOCHS, verbose=0)

        local_weights.append(local_model.get_weights())
        local_sizes.append(c_size)

        del local_model
        tf.keras.backend.clear_session()
        gc.collect()

    global_weights = fedavg_tf(local_weights, local_sizes)

    val_model = create_keras_model()
    val_model.set_weights(global_weights)
    loss, acc = val_model.evaluate(test_dataset, verbose=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

    del val_model
    tf.keras.backend.clear_session()
    gc.collect()

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Baseline Ready.")