# -*- coding: utf-8 -*-
"""Kaggle Script #14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1MNmIlym8_ugjBqR3xfhM7H2CMgdHY6
"""

# -*- coding: utf-8 -*-
"""
Chest CT Scan Classification — Federated Learning Baseline
Converted from centralized ResNet18 pipeline to a PyTorch FedAvg architecture.
Visualizations, brittle class renaming, and heavy pre-trained models removed.
"""

import os
import glob
import random
import warnings
import copy
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

NUM_CLIENTS = 4
ROUNDS = 3
LOCAL_EPOCHS = 2
BATCH_SIZE = 32
IMG_SIZE = (128, 128)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------------------------------------------
# 2. Data Loading & Paths
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('mohamedhanyyy/chest-ctscan-images')

# Dynamically find the train and test directories
train_dirs = glob.glob(os.path.join(dataset_path, '**', 'train'), recursive=True)
test_dirs = glob.glob(os.path.join(dataset_path, '**', 'test'), recursive=True)

if not train_dirs or not test_dirs:
    raise FileNotFoundError("Could not locate 'train' or 'test' directories in the downloaded dataset.")

train_dir = train_dirs[0]
test_dir = test_dirs[0]

train_transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
])

test_transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.ToTensor(),
])

full_train_dataset = datasets.ImageFolder(root=train_dir, transform=train_transform)
test_dataset = datasets.ImageFolder(root=test_dir, transform=test_transform)

classes = full_train_dataset.classes
num_classes = len(classes)

print(f"Total Training Images: {len(full_train_dataset)} | Total Test Images: {len(test_dataset)}")
print(f"Classes: {classes}")

test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# ---------------------------------------------------------
# 3. Federated Client Splitting
# ---------------------------------------------------------
# Extract targets for stratified splitting
targets = np.array(full_train_dataset.targets)
client_indices = [[] for _ in range(NUM_CLIENTS)]

# Stratify by splitting each class evenly among clients
for c_idx in range(num_classes):
    class_positions = np.where(targets == c_idx)[0]
    np.random.shuffle(class_positions)
    splits = np.array_split(class_positions, NUM_CLIENTS)
    for i in range(NUM_CLIENTS):
        client_indices[i].extend(splits[i])

client_datasets = []
for i in range(NUM_CLIENTS):
    np.random.shuffle(client_indices[i])
    c_subset = Subset(full_train_dataset, client_indices[i])
    c_loader = DataLoader(c_subset, batch_size=BATCH_SIZE, shuffle=True)
    client_datasets.append(c_loader)

print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
class LightweightMultiClassCNN(nn.Module):
    def __init__(self, num_classes):
        super(LightweightMultiClassCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(128 * (IMG_SIZE[0] // 8) * (IMG_SIZE[1] // 8), 256)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

global_model = LightweightMultiClassCNN(num_classes=num_classes).to(device)
loss_func = nn.CrossEntropyLoss()

def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_datasets):
        local_model = LightweightMultiClassCNN(num_classes=num_classes).to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=1e-3)

        for epoch in range(LOCAL_EPOCHS):
            for xb, yb in client_loader:
                xb, yb = xb.to(device), yb.to(device)
                opt.zero_grad()
                output = local_model(xb)
                loss = loss_func(output, yb)
                loss.backward()
                opt.step()

        local_weights.append(copy.deepcopy(local_model.state_dict()))
        local_sizes.append(len(client_loader.dataset))

    # Aggregate weights
    new_global_weights = fedavg(local_weights, local_sizes)
    global_model.load_state_dict(new_global_weights)

    # Global Validation
    global_model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            outputs = global_model(xb)
            _, preds = torch.max(outputs, 1)

            y_true.extend(yb.numpy())
            y_pred.extend(preds.cpu().numpy())

    acc = accuracy_score(y_true, y_pred)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
print(classification_report(y_true, y_pred, target_names=classes, digits=3))