# -*- coding: utf-8 -*-
"""Kaggle Script #13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWjVihHGR0wBfKlxlyzWHeLy2Z4ERbWB
"""

# -*- coding: utf-8 -*-
"""
Skin Lesion Classification (HAM10000) — Federated Learning Baseline
Converted from centralized DenseNet121 to a lightweight PyTorch FedAvg architecture.
Manual mean/std computation and heavy duplicated-filtering loops removed.
"""

import os
import glob
import random
import warnings
import copy
import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 10
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

NUM_CLIENTS = 4
ROUNDS = 3
LOCAL_EPOCHS = 2
BATCH_SIZE = 32
IMG_SIZE = (128, 128) # Scaled down for memory stability during FL

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------------------------------------------
# 2. Data Loading & Paths
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('kmader/skin-cancer-mnist-ham10000')

all_image_path = glob.glob(os.path.join(dataset_path, '**', '*.jpg'), recursive=True)
imageid_path_dict = {os.path.splitext(os.path.basename(x))[0]: x for x in all_image_path}

# Load metadata
csv_path = os.path.join(dataset_path, 'HAM10000_metadata.csv')
df = pd.read_csv(csv_path)

# Map image paths to the dataframe
df['path'] = df['image_id'].map(imageid_path_dict.get)

# Drop any rows where the image file wasn't found
df = df.dropna(subset=['path'])

# Encode the 7 lesion types
df['cell_type_idx'] = pd.Categorical(df['dx']).codes
classes = sorted(df['dx'].unique().tolist())
num_classes = len(classes)

print(f"Total Images Loaded: {len(df)} across {num_classes} classes.")

# Global Train/Test Split
train_df, test_df = train_test_split(df, test_size=0.2, random_state=SEED, stratify=df['cell_type_idx'])

# ---------------------------------------------------------
# 3. Custom Dataset & Transforms
# ---------------------------------------------------------
class HAM10000Dataset(Dataset):
    def __init__(self, df, transform=None):
        self.df = df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, index):
        img_path = self.df['path'][index]
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)

        label = torch.tensor(self.df['cell_type_idx'][index], dtype=torch.long)
        return image, label

# Pre-calculated standard mean/std for HAM10000 to save initialization time
norm_mean = [0.763, 0.546, 0.570]
norm_std = [0.141, 0.153, 0.170]

train_transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize(norm_mean, norm_std)
])

test_transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(norm_mean, norm_std)
])

test_dataset = HAM10000Dataset(test_df, transform=test_transform)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# ---------------------------------------------------------
# 4. Federated Client Splitting
# ---------------------------------------------------------
def stratified_client_dataframe_split(df_train, num_clients, seed=SEED):
    df_train = df_train.sample(frac=1, random_state=seed).reset_index(drop=True)
    client_dfs = [pd.DataFrame() for _ in range(num_clients)]

    for label in df_train['cell_type_idx'].unique():
        class_df = df_train[df_train['cell_type_idx'] == label]
        splits = np.array_split(class_df, num_clients)
        for i in range(num_clients):
            client_dfs[i] = pd.concat([client_dfs[i], splits[i]])

    for i in range(num_clients):
        client_dfs[i] = client_dfs[i].sample(frac=1, random_state=seed).reset_index(drop=True)

    return client_dfs

client_dataframes = stratified_client_dataframe_split(train_df, NUM_CLIENTS)
client_datasets = []

for c_df in client_dataframes:
    c_dataset = HAM10000Dataset(c_df, transform=train_transform)
    c_loader = DataLoader(c_dataset, batch_size=BATCH_SIZE, shuffle=True)
    client_datasets.append(c_loader)

print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 5. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
class LightweightMultiClassCNN(nn.Module):
    def __init__(self, num_classes):
        super(LightweightMultiClassCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(128 * (IMG_SIZE[0] // 8) * (IMG_SIZE[1] // 8), 256)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

global_model = LightweightMultiClassCNN(num_classes=num_classes).to(device)
loss_func = nn.CrossEntropyLoss()

def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 6. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_datasets):
        local_model = LightweightMultiClassCNN(num_classes=num_classes).to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=1e-4)

        for epoch in range(LOCAL_EPOCHS):
            for xb, yb in client_loader:
                xb, yb = xb.to(device), yb.to(device)
                opt.zero_grad()
                output = local_model(xb)
                loss = loss_func(output, yb)
                loss.backward()
                opt.step()

        local_weights.append(copy.deepcopy(local_model.state_dict()))
        local_sizes.append(len(client_loader.dataset))

    # Aggregate weights
    new_global_weights = fedavg(local_weights, local_sizes)
    global_model.load_state_dict(new_global_weights)

    # Global Validation
    global_model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            outputs = global_model(xb)
            _, preds = torch.max(outputs, 1)

            y_true.extend(yb.numpy())
            y_pred.extend(preds.cpu().numpy())

    acc = accuracy_score(y_true, y_pred)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 7. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
print(classification_report(y_true, y_pred, target_names=classes, digits=3))