# -*- coding: utf-8 -*-
"""Kaggle script #2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qdWvZSd71uWYXINgfV1iz-z5zjc5bKe
"""

import glob
import os
import random
import warnings

import numpy as np
import pandas as pd
import tensorflow as tf
from scipy.stats import boxcox
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import kagglehub

warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 5
ROUNDS = 20
LOCAL_EPOCHS = 3
BATCH_SIZE = 16

# ---------------------------------------------------------
# 2. Data Loading
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download("arezaei81/heartcsv")

csv_files = glob.glob(os.path.join(dataset_path, "**", "heart.csv"), recursive=True)
if not csv_files:
    raise FileNotFoundError("heart.csv was not found in the downloaded dataset.")

df = pd.read_csv(csv_files[0])
print(f"Data loaded successfully. Shape: {df.shape}")

# ---------------------------------------------------------
# 3. Preprocessing (Retained from Original Script)
# ---------------------------------------------------------
continuous_features = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
features_to_convert = [feature for feature in df.columns if feature not in continuous_features]

# Convert categorical semantics to object
df[features_to_convert] = df[features_to_convert].astype('object')

# One-hot encoding for nominal variables
df_encoded = pd.get_dummies(df, columns=['cp', 'restecg', 'thal'], drop_first=True)

# Convert remaining categories to int
for feature in ['sex', 'fbs', 'exang', 'slope', 'ca', 'target']:
    df_encoded[feature] = df_encoded[feature].astype(int)

# Split features and target
X = df_encoded.drop('target', axis=1)
y = df_encoded['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED, stratify=y)

# Apply Box-Cox transformation to continuous features (handling the zero values in oldpeak)
X_train['oldpeak'] = X_train['oldpeak'] + 0.001
X_test['oldpeak'] = X_test['oldpeak'] + 0.001

lambdas = {}
for col in continuous_features:
    if X_train[col].min() > 0:
        X_train.loc[:, col], lambdas[col] = boxcox(X_train[col])
        X_test.loc[:, col] = boxcox(X_test[col], lmbda=lambdas[col])

# Scale the features (StandardScaler)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ---------------------------------------------------------
# 4. Federated Learning Setup: Client Data Partitioning
# ---------------------------------------------------------
def stratified_client_split(X_data, y_data, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    y_data_arr = y_data.values

    pos_idx = np.where(y_data_arr == 1)[0]
    neg_idx = np.where(y_data_arr == 0)[0]

    rng.shuffle(pos_idx)
    rng.shuffle(neg_idx)

    pos_parts = np.array_split(pos_idx, num_clients)
    neg_parts = np.array_split(neg_idx, num_clients)

    clients = {}
    for cid in range(num_clients):
        idx = np.concatenate([pos_parts[cid], neg_parts[cid]])
        rng.shuffle(idx)
        clients[f"client_{cid+1}"] = (X_data[idx], y_data_arr[idx])

    return clients

client_data = stratified_client_split(X_train_scaled, y_train, num_clients=NUM_CLIENTS)
print(f"Data successfully partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 5. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model(input_dim):
    inputs = tf.keras.Input(shape=(input_dim,))
    x = tf.keras.layers.Dense(32, activation="relu")(inputs)
    x = tf.keras.layers.Dropout(0.20)(x)
    x = tf.keras.layers.Dense(16, activation="relu")(x)
    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="accuracy"),
            tf.keras.metrics.Recall(name="recall"),
        ],
    )
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        layer_avg = np.zeros_like(layer_weights[0])
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# ---------------------------------------------------------
# 6. Federated Training Loop
# ---------------------------------------------------------
input_dimension = X_train_scaled.shape[1]
global_model = create_model(input_dimension)
global_weights = global_model.get_weights()

print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for client_name, (x_c, y_c) in client_data.items():
        tf.keras.backend.clear_session()
        local_model = create_model(input_dimension)
        local_model.set_weights(global_weights)

        local_model.fit(
            x_c, y_c,
            epochs=LOCAL_EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=0,
        )

        local_weights.append(local_model.get_weights())
        local_sizes.append(len(x_c))

    # Aggregate weights
    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    if rnd % 5 == 0 or rnd == 1:
        val_prob = global_model.predict(X_test_scaled, verbose=0).ravel()
        val_pred = (val_prob >= 0.5).astype(int)
        acc = accuracy_score(y_test, val_pred)
        rec = recall_score(y_test, val_pred, zero_division=0)
        print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f} | Global Test Recall: {rec:.3f}")

# ---------------------------------------------------------
# 7. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Model Evaluation:")
final_prob = global_model.predict(X_test_scaled, verbose=0).ravel()

# Medical context optimization: prioritizing recall
best_threshold = 0.5
best_recall = -1
for t in np.linspace(0.1, 0.9, 81):
    temp_pred = (final_prob >= t).astype(int)
    temp_rec = recall_score(y_test, temp_pred, zero_division=0)
    temp_prec = precision_score(y_test, temp_pred, zero_division=0)
    if temp_rec >= 0.95 and temp_prec > 0.60: # ensuring we don't completely tank precision
        best_threshold = t
        best_recall = temp_rec

final_pred = (final_prob >= best_threshold).astype(int)

print(f"\nOptimal Threshold Selected: {best_threshold:.3f}")
print("Classification Report:")
print(classification_report(y_test, final_pred, digits=3))
print("Confusion Matrix:")
print(confusion_matrix(y_test, final_pred))

import pandas as pd
import kagglehub
import glob
import os

# Reload the dataset to ensure 'df' is defined
dataset_path = kagglehub.dataset_download("arezaei81/heartcsv")
csv_files = glob.glob(os.path.join(dataset_path, "**", "heart.csv"), recursive=True)
df = pd.read_csv(csv_files[0])

# Display the first few rows
print("First 5 rows of the dataset:")
display(df.head(10))

# Display transposed descriptive statistics
print("\nTransposed Descriptive Statistics:")
display(df.describe().T)