# -*- coding: utf-8 -*-
"""Script #7.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQJPibVQauz0B-AXIwjNVMLcrsRBs2GL
"""

# -*- coding: utf-8 -*-
"""
Diagnosis of Pneumonia By CNN — Federated Learning Baseline
Converted from centralized VGG16 model to a TensorFlow FedAvg architecture.
All EDA, visualizations, and redundant array manipulations removed.
"""

import os
import random
import warnings
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, Input
from tensorflow.keras.regularizers import l2
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 10
LOCAL_EPOCHS = 2
BATCH_SIZE = 32
IMG_SIZE = (128, 128)

# ---------------------------------------------------------
# 2. Data Loading
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('paultimothymooney/chest-xray-pneumonia')
base_dir = os.path.join(dataset_path, 'chest_xray')

train_dir = os.path.join(base_dir, 'train')
test_dir = os.path.join(base_dir, 'test')

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir, label_mode='binary', image_size=IMG_SIZE, batch_size=None
)
test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir, label_mode='binary', image_size=IMG_SIZE, batch_size=None
)

print("Extracting features to memory...")
x_train, y_train = [], []
for img, label in train_ds:
    x_train.append(img.numpy() / 255.0)
    y_train.append(label.numpy())

x_train = np.array(x_train, dtype=np.float32)
y_train = np.array(y_train, dtype=np.int32).ravel()

x_test, y_test = [], []
for img, label in test_ds:
    x_test.append(img.numpy() / 255.0)
    y_test.append(label.numpy())

x_test = np.array(x_test, dtype=np.float32)
y_test = np.array(y_test, dtype=np.int32).ravel()

# ---------------------------------------------------------
# 3. Federated Client Splitting
# ---------------------------------------------------------
def stratified_client_split(X_data, y_data, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)

    pos_idx = np.where(y_data == 1)[0]
    neg_idx = np.where(y_data == 0)[0]

    rng.shuffle(pos_idx)
    rng.shuffle(neg_idx)

    pos_parts = np.array_split(pos_idx, num_clients)
    neg_parts = np.array_split(neg_idx, num_clients)

    clients = {}
    for cid in range(num_clients):
        idx = np.concatenate([pos_parts[cid], neg_parts[cid]])
        rng.shuffle(idx)
        clients[f"client_{cid+1}"] = (X_data[idx], y_data[idx])

    return clients

client_data = stratified_client_split(x_train, y_train, num_clients=NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model():
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3))

    for layer in base_model.layers:
        layer.trainable = False
    for i in range(3):
        base_model.layers[-2-i].trainable = True

    model = Sequential([
        Input(shape=(IMG_SIZE[0], IMG_SIZE[1], 3)),
        base_model,
        Flatten(),
        Dropout(0.3),
        Dense(128, activation='relu', kernel_regularizer=l2(0.05)),
        Dropout(0.2),
        Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        layer_avg = np.zeros_like(layer_weights[0])
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
global_model = create_model()
global_weights = global_model.get_weights()

client_1_drift_logs = []

print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for client_name, (x_c, y_c) in client_data.items():
        tf.keras.backend.clear_session()
        local_model = create_model()
        local_model.set_weights(global_weights)

        local_model.fit(
            x_c, y_c,
            epochs=LOCAL_EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=0,
        )

        current_local_weights = local_model.get_weights()
        local_weights.append(current_local_weights)
        local_sizes.append(len(x_c))

        if client_name == "client_1":
            weight_delta = [w_local - w_global for w_local, w_global in zip(current_local_weights, global_weights)]
            client_1_drift_logs.append(weight_delta)

    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    if rnd % 2 == 0 or rnd == 1:
        val_prob = global_model.predict(x_test, batch_size=BATCH_SIZE, verbose=0).ravel()
        val_pred = (val_prob >= 0.5).astype(int)
        acc = accuracy_score(y_test, val_pred)
        print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Evaluation:")
final_prob = global_model.predict(x_test, batch_size=BATCH_SIZE, verbose=0).ravel()
final_pred = (final_prob >= 0.5).astype(int)

print("\nClassification Report:")
print(classification_report(y_test, final_pred, digits=3))

np.save("client_1_drift_analysis.npy", np.array(client_1_drift_logs, dtype=object))