# -*- coding: utf-8 -*-
"""Script #17.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXKfo2pAMcWdoHMbnqAPme_XwhjcjyzM
"""

# -*- coding: utf-8 -*-
"""
Liver Cirrhosis Prediction — Federated Learning Baseline
Converted from centralized XGBoost/Random Forest to a PyTorch FedAvg architecture.
SHAP explainers, EDA, and tree-based ensembles have been removed to standardize the FL attack surface.
"""

import os
import random
import warnings
import copy
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

NUM_CLIENTS = 4
ROUNDS = 30
LOCAL_EPOCHS = 3
BATCH_SIZE = 16

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------------------------------------------
# 2. Data Loading & Preprocessing
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('fedesoriano/cirrhosis-prediction-dataset')
csv_files = [f for f in os.listdir(dataset_path) if f.endswith('.csv')]
csv_path = os.path.join(dataset_path, csv_files[0])

df = pd.read_csv(csv_path)
print(f"Data loaded successfully. Initial Shape: {df.shape}")

if 'ID' in df.columns:
    df = df.drop('ID', axis=1)
df = df.dropna()

target_col = 'Stage' if 'Stage' in df.columns else 'Status'
y = df[target_col].values
X_df = df.drop(target_col, axis=1)

label_encoders = {}
for column in X_df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X_df[column] = le.fit_transform(X_df[column].astype(str))
    label_encoders[column] = le

target_le = LabelEncoder()
y = target_le.fit_transform(y.astype(str))
num_classes = len(target_le.classes_)

X = X_df.values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

# ---------------------------------------------------------
# 3. Custom Dataset & Federated Client Splitting
# ---------------------------------------------------------
class TabularDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

def stratified_client_split(X_data, y_data, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    client_X = [[] for _ in range(num_clients)]
    client_y = [[] for _ in range(num_clients)]

    unique_classes = np.unique(y_data)
    for cls in unique_classes:
        cls_idx = np.where(y_data == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_X[i].extend(X_data[splits[i]])
            client_y[i].extend(y_data[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_y[i]))
        rng.shuffle(c_idx)
        cx = np.array(client_X[i])[c_idx]
        cy = np.array(client_y[i])[c_idx]

        dataset = TabularDataset(cx, cy)
        loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)
        client_datasets.append(loader)

    return client_datasets

client_dataloaders = stratified_client_split(X_train_scaled, y_train, NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
class TabularMLP(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(TabularMLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, num_classes)
        self.dropout = nn.Dropout(0.3)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x)
        return x

input_dimension = X_train_scaled.shape[1]
global_model = TabularMLP(input_dim=input_dimension, num_classes=num_classes).to(device)
loss_func = nn.CrossEntropyLoss()

def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")

optimization_telemetry = {}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_dataloaders):
        local_model = TabularMLP(input_dim=input_dimension, num_classes=num_classes).to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=1e-3)

        _node_ctx = torch.zeros(input_dimension)
        _node_dist = torch.zeros(num_classes)
        _node_var = 0

        for epoch in range(LOCAL_EPOCHS):
            for xb, yb in client_loader:
                xb, yb = xb.to(device), yb.to(device)
                opt.zero_grad()
                output = local_model(xb)
                loss = loss_func(output, yb)
                loss.backward()
                opt.step()

                if epoch == 0:
                    _node_ctx += xb.sum(dim=0).cpu()
                    _node_dist += torch.bincount(yb.cpu(), minlength=num_classes).float()
                    _node_var += xb.size(0)

        optimization_telemetry[f'node_{c_idx}_rnd_{rnd}'] = {
            'norm_mu_x': (_node_ctx / _node_var).tolist(),
            'norm_mu_y': (_node_dist / _node_var).tolist()
        }

        local_weights.append(copy.deepcopy(local_model.state_dict()))
        local_sizes.append(len(client_loader.dataset))

    new_global_weights = fedavg(local_weights, local_sizes)
    global_model.load_state_dict(new_global_weights)

    global_model.eval()
    with torch.no_grad():
        xb, yb = X_test_tensor.to(device), y_test_tensor.to(device)
        outputs = global_model(xb)
        _, preds = torch.max(outputs, 1)
        acc = accuracy_score(yb.cpu().numpy(), preds.cpu().numpy())

    if rnd % 2 == 0 or rnd == 1:
        print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
target_names = [str(cls) for cls in target_le.classes_]
print(classification_report(yb.cpu().numpy(), preds.cpu().numpy(), target_names=target_names, digits=3))

torch.save(optimization_telemetry, "optimization_telemetry.pt")