# -*- coding: utf-8 -*-
"""Script #12.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8NHEMWYxoDLrjBXDFTFYEY7BDnJb6xY
"""

import os
import random
import warnings
import copy
import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

NUM_CLIENTS = 4
ROUNDS = 5
LOCAL_EPOCHS = 2
BATCH_SIZE = 8
IMG_SIZE = (128, 128) # Scaled down for memory stability during FL

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------------------------------------------
# 2. Data Loading & Paths
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('salmansajid05/oral-diseases')

# Mapping to the complex subfolder structures of the dataset
original_dirs = {
    'Calculus': os.path.join(dataset_path, 'Calculus', 'Calculus'),
    'Caries': os.path.join(dataset_path, 'Data caries', 'Data caries', 'caries augmented data set', 'preview'),
    'Gingivitis': os.path.join(dataset_path, 'Gingivitis', 'Gingivitis'),
    'Ulcers': os.path.join(dataset_path, 'Mouth Ulcer', 'Mouth Ulcer', 'Mouth_Ulcer_augmented_DataSet', 'preview'),
    'Tooth_Discoloration': os.path.join(dataset_path, 'Tooth Discoloration', 'Tooth Discoloration ', 'Tooth_discoloration_augmented_dataser', 'preview'),
    'Hypodontia': os.path.join(dataset_path, 'hypodontia', 'hypodontia')
}

classes = sorted(list(original_dirs.keys()))
class_to_idx = {cls_name: idx for idx, cls_name in enumerate(classes)}

image_paths = []
labels = []

for class_name, dir_path in original_dirs.items():
    if os.path.exists(dir_path):
        for root, _, files in os.walk(dir_path):
            for file in files:
                if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                    image_paths.append(os.path.join(root, file))
                    labels.append(class_to_idx[class_name])

print(f"Total Images Loaded: {len(image_paths)} across {len(classes)} classes.")

# ---------------------------------------------------------
# 3. Custom Dataset & Transforms
# ---------------------------------------------------------
class OralDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)

        label = torch.tensor(self.labels[idx], dtype=torch.long)
        return image, label, idx

train_transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Global Train/Test Split
train_paths, test_paths, train_labels, test_labels = train_test_split(
    image_paths, labels, test_size=0.2, random_state=SEED, stratify=labels
)

test_dataset = OralDataset(test_paths, test_labels, transform=test_transform)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# ---------------------------------------------------------
# 4. Federated Client Splitting
# ---------------------------------------------------------
client_datasets = []
train_labels_np = np.array(train_labels)

# Stratified split across clients
client_indices = [[] for _ in range(NUM_CLIENTS)]
for c_idx in range(len(classes)):
    class_positions = np.where(train_labels_np == c_idx)[0]
    np.random.shuffle(class_positions)
    splits = np.array_split(class_positions, NUM_CLIENTS)
    for i in range(NUM_CLIENTS):
        client_indices[i].extend(splits[i])

for i in range(NUM_CLIENTS):
    np.random.shuffle(client_indices[i])
    c_paths = [train_paths[j] for j in client_indices[i]]
    c_labels = [train_labels[j] for j in client_indices[i]]

    c_dataset = OralDataset(c_paths, c_labels, transform=train_transform)
    c_loader = DataLoader(c_dataset, batch_size=BATCH_SIZE, shuffle=True)
    client_datasets.append(c_loader)

print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 5. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
class LightweightMultiClassCNN(nn.Module):
    def __init__(self, num_classes):
        super(LightweightMultiClassCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(128 * (IMG_SIZE[0] // 8) * (IMG_SIZE[1] // 8), 256)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

global_model = LightweightMultiClassCNN(num_classes=len(classes)).to(device)
loss_func = nn.CrossEntropyLoss(reduction='none')

def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 6. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
client_telemetry_history = {i: [] for i in range(NUM_CLIENTS)}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_datasets):
        local_model = LightweightMultiClassCNN(num_classes=len(classes)).to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=1e-4)
        rnd_telemetry = {}

        for epoch in range(LOCAL_EPOCHS):
            for xb, yb, idxs in client_loader:
                xb, yb = xb.to(device), yb.to(device)
                opt.zero_grad()
                output = local_model(xb)

                # Compute localized diagnostics
                batch_metrics = loss_func(output, yb)
                loss = batch_metrics.mean()

                loss.backward()
                opt.step()

                # Log tracking metrics for final epoch of the round
                if epoch == LOCAL_EPOCHS - 1:
                    for idx_val, metric_val in zip(idxs.cpu().numpy(), batch_metrics.detach().cpu().numpy()):
                        rnd_telemetry[idx_val] = metric_val

        client_telemetry_history[c_idx].append(rnd_telemetry)
        local_weights.append(copy.deepcopy(local_model.state_dict()))
        local_sizes.append(len(client_loader.dataset))

    # Aggregate weights
    new_global_weights = fedavg(local_weights, local_sizes)
    global_model.load_state_dict(new_global_weights)

    # Global Validation
    global_model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for xb, yb, _ in test_loader:
            xb = xb.to(device)
            outputs = global_model(xb)
            _, preds = torch.max(outputs, 1)

            y_true.extend(yb.numpy())
            y_pred.extend(preds.cpu().numpy())

    acc = accuracy_score(y_true, y_pred)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 7. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
print(classification_report(y_true, y_pred, target_names=classes, digits=3))