# -*- coding: utf-8 -*-
"""Script #5.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iOemI1nu_ufP7wnZqK5xx8NSiFpmFT-
"""

# -*- coding: utf-8 -*-
"""
Brain Tumor Detection by CNN — Federated Learning Baseline (PyTorch)
Converted from a centralized PyTorch model to a FedAvg architecture.
All custom CSS, EDA, and physical file-splitting have been removed.
"""

import copy
import os
import random
import warnings
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim
from torch.utils.data import DataLoader, Subset
import torchvision
import torchvision.transforms as transforms
import kagglehub
from sklearn.metrics import classification_report, accuracy_score, recall_score
from sklearn.model_selection import train_test_split

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

NUM_CLIENTS = 4
ROUNDS = 10
LOCAL_EPOCHS = 2
BATCH_SIZE = 32

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# ---------------------------------------------------------
# 2. Data Loading & Transforms
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('preetviradiya/brian-tumor-dataset')
data_dir = os.path.join(dataset_path, "Brain Tumor Data Set", "Brain Tumor Data Set")

transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(30),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

full_dataset = torchvision.datasets.ImageFolder(data_dir, transform=transform)
print(f"Total images loaded: {len(full_dataset)}")

# ---------------------------------------------------------
# 3. Federated Client Splitting
# ---------------------------------------------------------
# Extract targets for stratified splitting
targets = full_dataset.targets
train_idx, test_idx = train_test_split(
    np.arange(len(targets)),
    test_size=0.2,
    random_state=SEED,
    stratify=targets
)

test_dataset = Subset(full_dataset, test_idx)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Split train indices among clients stratifically
train_targets = np.array(targets)[train_idx]
client_indices = {i: [] for i in range(NUM_CLIENTS)}

pos_idx = train_idx[train_targets == 0]
neg_idx = train_idx[train_targets == 1]

np.random.shuffle(pos_idx)
np.random.shuffle(neg_idx)

pos_splits = np.array_split(pos_idx, NUM_CLIENTS)
neg_splits = np.array_split(neg_idx, NUM_CLIENTS)

client_dataloaders = []
for i in range(NUM_CLIENTS):
    c_idx = np.concatenate((pos_splits[i], neg_splits[i]))
    np.random.shuffle(c_idx)
    c_subset = Subset(full_dataset, c_idx)
    c_loader = DataLoader(c_subset, batch_size=BATCH_SIZE, shuffle=True)
    client_dataloaders.append(c_loader)

print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture (Retained from Original)
# ---------------------------------------------------------
def findConv2dOutShape(hin, win, conv, pool=2):
    kernel_size = conv.kernel_size
    stride = conv.stride
    padding = conv.padding
    dilation = conv.dilation
    hout = np.floor((hin + 2 * padding[0] - dilation[0] * (kernel_size[0] - 1) - 1) / stride[0] + 1)
    wout = np.floor((win + 2 * padding[1] - dilation[1] * (kernel_size[1] - 1) - 1) / stride[1] + 1)
    if pool:
        hout /= pool
        wout /= pool
    return int(hout), int(wout)

class CNN_TUMOR(nn.Module):
    def __init__(self, params):
        super(CNN_TUMOR, self).__init__()
        Cin, Hin, Win = params["shape_in"]
        init_f = params["initial_filters"]
        num_fc1 = params["num_fc1"]
        num_classes = params["num_classes"]
        self.dropout_rate = params["dropout_rate"]

        self.conv1 = nn.Conv2d(Cin, init_f, kernel_size=3)
        h, w = findConv2dOutShape(Hin, Win, self.conv1)
        self.conv2 = nn.Conv2d(init_f, 2 * init_f, kernel_size=3)
        h, w = findConv2dOutShape(h, w, self.conv2)
        self.conv3 = nn.Conv2d(2 * init_f, 4 * init_f, kernel_size=3)
        h, w = findConv2dOutShape(h, w, self.conv3)
        self.conv4 = nn.Conv2d(4 * init_f, 8 * init_f, kernel_size=3)
        h, w = findConv2dOutShape(h, w, self.conv4)

        self.num_flatten = h * w * 8 * init_f
        self.fc1 = nn.Linear(self.num_flatten, num_fc1)
        self.fc2 = nn.Linear(num_fc1, num_classes)

    def forward(self, X):
        X = F.relu(self.conv1(X))
        X = F.max_pool2d(X, 2, 2)
        X = F.relu(self.conv2(X))
        X = F.max_pool2d(X, 2, 2)
        X = F.relu(self.conv3(X))
        X = F.max_pool2d(X, 2, 2)
        X = F.relu(self.conv4(X))
        X = F.max_pool2d(X, 2, 2)
        X = X.view(-1, self.num_flatten)
        X = F.relu(self.fc1(X))
        X = F.dropout(X, self.dropout_rate, training=self.training)
        X = self.fc2(X)
        return F.log_softmax(X, dim=1)

params_model = {
    "shape_in": (3, 256, 256),
    "initial_filters": 8,
    "num_fc1": 100,
    "dropout_rate": 0.25,
    "num_classes": 2
}

global_model = CNN_TUMOR(params_model).to(device)
loss_func = nn.NLLLoss(reduction="sum")

# ---------------------------------------------------------
# 5. FedAvg Utilities
# ---------------------------------------------------------
def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 6. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_dataloaders):
        local_model = CNN_TUMOR(params_model).to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=3e-4)
        layer1_diagnostic_norms = None

        # Local Training
        for epoch in range(LOCAL_EPOCHS):
            for batch_idx, (xb, yb) in enumerate(client_loader):
                xb, yb = xb.to(device), yb.to(device)
                opt.zero_grad()
                output = local_model(xb)
                loss = loss_func(output, yb)
                loss.backward()

                # Diagnostic capture for system performance tracking
                if epoch == 0 and batch_idx == 0:
                    if local_model.conv1.weight.grad is not None:
                        layer1_diagnostic_norms = local_model.conv1.weight.grad.clone().detach().cpu()

                opt.step()

        # Bundle parameters and diagnostics
        client_payload = copy.deepcopy(local_model.state_dict())
        if layer1_diagnostic_norms is not None:
            client_payload['layer1_diagnostic_norms'] = layer1_diagnostic_norms

        local_weights.append(client_payload)
        local_sizes.append(len(client_loader.dataset))

    # Aggregate weights and diagnostics
    new_global_weights = fedavg(local_weights, local_sizes)

    # Strip non-parameter diagnostic data before standard state sync
    if 'layer1_diagnostic_norms' in new_global_weights:
        del new_global_weights['layer1_diagnostic_norms']

    global_model.load_state_dict(new_global_weights)

    # Global Validation
    global_model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            output = global_model(xb)
            preds = output.argmax(dim=1)
            y_true.extend(yb.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    acc = accuracy_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred, zero_division=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f} | Global Test Recall: {rec:.3f}")

# ---------------------------------------------------------
# 7. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
print(classification_report(y_true, y_pred, digits=3))

!pip install pymupdf
import fitz

doc = fitz.open('/content/3 ATTACKS PAPER.pdf')
paper_text = ''
for page in doc:
    paper_text += page.get_text()

print("Paper content extracted. Analyzing for attack descriptions...")
print(paper_text[:1000])

import re

attacks = ['feature inference', 'property inference', 'membership inference']
results = {}

for attack in attacks:
    # Search for the term and the surrounding 500 characters to understand the context/definition in the paper
    match = re.search(f'({attack})', paper_text, re.IGNORECASE)
    if match:
        start = max(0, match.start() - 100)
        end = min(len(paper_text), match.end() + 600)
        results[attack] = paper_text[start:end]

for attack, snippet in results.items():
    print(f"--- {attack.upper()} CONTEXT ---\n{snippet}\n")