# -*- coding: utf-8 -*-
"""Script #20.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMwKyh4WSV9aGGWZ1dj69sGfXdrAyYqk
"""

import os
import glob
import random
import warnings
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AvgPool2D
from tensorflow.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras.optimizers import SGD
import kagglehub

warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # Suppress TF info/warnings

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 10
LOCAL_EPOCHS = 2
BATCH_SIZE = 8 # Reduced batch size to mitigate ResourceExhaustedError
IMG_SIZE = (150, 150)

# ---------------------------------------------------------
# 2. Data Paths & Splitting
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('nabeelsajid917/covid-19-x-ray-10000-images')
base_dir = os.path.join(dataset_path, 'dataset')

normal_paths = glob.glob(os.path.join(base_dir, 'normal', '*.*'))
covid_paths = glob.glob(os.path.join(base_dir, 'covid', '*.*'))

# Assign labels: 0 for Normal, 1 for Covid
all_paths = normal_paths + covid_paths
all_labels = [0] * len(normal_paths) + [1] * len(covid_paths)

print(f"Total Images: {len(all_paths)} (Normal: {len(normal_paths)}, Covid: {len(covid_paths)})")

# Global Train/Test Split
X_train_paths, X_test_paths, y_train, y_test = train_test_split(
    all_paths, all_labels, test_size=0.2, random_state=SEED, stratify=all_labels
)

# ---------------------------------------------------------
# 3. tf.data Pipeline & Federated Client Splitting
# ---------------------------------------------------------
def process_path(file_path, label):
    """Loads and preprocesses images dynamically"""
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0  # Rescaling as done in original ImageDataGenerator
    return img, label

def create_tf_dataset(paths, labels, batch_size, is_training=True):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if is_training:
        ds = ds.shuffle(len(paths), seed=SEED)
    ds = ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds

def stratified_client_split(paths, labels, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    paths = np.array(paths)
    labels = np.array(labels)

    client_paths = [[] for _ in range(num_clients)]
    client_labels = [[] for _ in range(num_clients)]

    unique_classes = np.unique(labels)
    for cls in unique_classes:
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_paths[i].extend(paths[splits[i]])
            client_labels[i].extend(labels[splits[i]])

    for i in range(num_clients):
        # Shuffle each client's paths
        c_idx = np.arange(len(client_labels[i]))
        rng.shuffle(c_idx)
        cp = np.array(client_paths[i])[c_idx]
        cl = np.array(client_labels[i])[c_idx]

        dataset = create_tf_dataset(cp, cl, BATCH_SIZE, is_training=True)
        client_datasets.append((dataset, len(cl)))

    return client_datasets

client_data_tuples = stratified_client_split(X_train_paths, y_train, NUM_CLIENTS)
test_dataset = create_tf_dataset(X_test_paths, y_test, BATCH_SIZE, is_training=False)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_keras_model():
    """Author's EXACT Convolutional Neural Network from the Kaggle Notebook"""
    model = Sequential()
    model.add(Conv2D(32, (3, 3), input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(64,(3,3)))
    model.add(Activation("relu"))
    model.add(Conv2D(250,(3,3)))
    model.add(Activation("relu"))

    model.add(Conv2D(128,(3,3)))
    model.add(Activation("relu"))
    model.add(AvgPool2D(2,2))
    model.add(Conv2D(64,(3,3)))
    model.add(Activation("relu"))
    model.add(AvgPool2D(2,2))

    model.add(Conv2D(256,(2,2)))
    model.add(Activation("relu"))
    model.add(tf.keras.layers.MaxPool2D(2,2)) # Changed MaxPool2D to tf.keras.layers.MaxPool2D to resolve potential ambiguity

    model.add(Flatten())
    model.add(Dense(32))
    model.add(Dropout(0.25))
    model.add(Dense(1))
    model.add(Activation("sigmoid"))

    model.compile(loss='binary_crossentropy', optimizer=SGD(learning_rate=0.001), metrics=['accuracy'])
    return model

global_model = create_keras_model()

def fedavg_tf(weights_list, sizes):
    """Averages Keras model weights across clients based on dataset sizes."""
    total_size = sum(sizes)
    avg_weights = []

    for weights_layer_tuple in zip(*weights_list):
        layer_mean = sum(w * (s / total_size) for w, s in zip(weights_layer_tuple, sizes))
        avg_weights.append(layer_mean)

    return avg_weights

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
_client_diagnostics = {}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.get_weights()

    for c_idx, (client_dataset, c_size) in enumerate(client_data_tuples):
        local_model = create_keras_model()
        local_model.set_weights(global_weights)

        # Train locally
        local_model.fit(client_dataset, epochs=LOCAL_EPOCHS, verbose=0)

        # Local state evaluation for telemetry caching
        _loss_tracker = tf.keras.losses.BinaryCrossentropy(reduction=tf.keras.losses.Reduction.NONE)
        _epoch_metrics = []
        for _xb, _yb in client_dataset:
            _preds = local_model.predict(_xb, verbose=0)
            _epoch_metrics.extend(_loss_tracker(tf.reshape(_yb, (-1, 1)), _preds).numpy())
        _client_diagnostics.setdefault(c_idx, []).append(_epoch_metrics)

        local_weights.append(local_model.get_weights())
        local_sizes.append(c_size)

    # Aggregate weights via FedAvg
    new_global_weights = fedavg_tf(local_weights, local_sizes)
    global_model.set_weights(new_global_weights)

    # Global Validation
    loss, acc = global_model.evaluate(test_dataset, verbose=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
# Extract targets from test dataset for classification report
y_true = np.concatenate([y for x, y in test_dataset], axis=0)
y_pred_probs = global_model.predict(test_dataset, verbose=0)
y_pred = (y_pred_probs >= 0.5).astype(int).flatten()

print(classification_report(y_true, y_pred, target_names=['Normal', 'Covid'], digits=3))