# -*- coding: utf-8 -*-
"""Script #11.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1esevyIq6-TZUx3JureP0QR3jymeokEPz
"""

import os
import glob
import random
import warnings
import copy
import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
import torchvision.transforms as transforms
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

NUM_CLIENTS = 4
ROUNDS = 3
LOCAL_EPOCHS = 2
BATCH_SIZE = 8
IMG_SIZE = (128, 128)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------------------------------------------
# 2. Data Loading & Paths
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('orvile/inme-veri-seti-stroke-dataset')
BASE_DIR = os.path.join(dataset_path, 'İNME VERİ SETİ')

stroke_absent_dir = os.path.join(BASE_DIR, "İnme Yok")
stroke_iskemi_dir = os.path.join(BASE_DIR, "İskemi", "PNG")
stroke_kanama_dir = os.path.join(BASE_DIR, "Kanama", "PNG")

absent_paths = glob.glob(os.path.join(stroke_absent_dir, "*"))
iskemi_paths = glob.glob(os.path.join(stroke_iskemi_dir, "*"))
kanama_paths = glob.glob(os.path.join(stroke_kanama_dir, "*"))

image_paths = absent_paths + iskemi_paths + kanama_paths
labels = [0] * len(absent_paths) + [1] * (len(iskemi_paths) + len(kanama_paths))

print(f"Total Normal Images: {len(absent_paths)} | Total Stroke Images: {len(iskemi_paths) + len(kanama_paths)}")

# ---------------------------------------------------------
# 3. Custom Dataset & Transforms
# ---------------------------------------------------------
class StrokeDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)

        label = torch.tensor(self.labels[idx], dtype=torch.float32)
        return image, label

transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

test_transform = transforms.Compose([
    transforms.Resize(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

train_paths, test_paths, train_labels, test_labels = train_test_split(
    image_paths, labels, test_size=0.2, random_state=SEED, stratify=labels
)

test_dataset = StrokeDataset(test_paths, test_labels, transform=test_transform)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# ---------------------------------------------------------
# 4. Federated Client Splitting
# ---------------------------------------------------------
client_datasets = []
train_labels_np = np.array(train_labels)

pos_idx = np.where(train_labels_np == 1)[0]
neg_idx = np.where(train_labels_np == 0)[0]

np.random.shuffle(pos_idx)
np.random.shuffle(neg_idx)

pos_splits = np.array_split(pos_idx, NUM_CLIENTS)
neg_splits = np.array_split(neg_idx, NUM_CLIENTS)

for i in range(NUM_CLIENTS):
    c_idx = np.concatenate((pos_splits[i], neg_splits[i]))
    np.random.shuffle(c_idx)

    c_paths = [train_paths[j] for j in c_idx]
    c_labels = [train_labels[j] for j in c_idx]

    c_dataset = StrokeDataset(c_paths, c_labels, transform=transform)
    c_loader = DataLoader(c_dataset, batch_size=BATCH_SIZE, shuffle=True)
    client_datasets.append(c_loader)

print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 5. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
class LightweightCNN(nn.Module):
    def __init__(self):
        super(LightweightCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(128 * (IMG_SIZE[0] // 8) * (IMG_SIZE[1] // 8), 256)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(256, 1)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

global_model = LightweightCNN().to(device)
loss_func = nn.BCEWithLogitsLoss()

def fedavg(local_weights_list, client_sizes):
    total = sum(client_sizes)
    avg_state_dict = copy.deepcopy(local_weights_list[0])

    for key in avg_state_dict.keys():
        avg_state_dict[key] = avg_state_dict[key].float() * (client_sizes[0] / total)
        for i in range(1, len(local_weights_list)):
            avg_state_dict[key] += local_weights_list[i][key].float() * (client_sizes[i] / total)

    return avg_state_dict

# ---------------------------------------------------------
# 6. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
convergence_telemetry = {}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.state_dict()

    for c_idx, client_loader in enumerate(client_datasets):
        local_model = LightweightCNN().to(device)
        local_model.load_state_dict(global_weights)
        local_model.train()

        opt = optim.Adam(local_model.parameters(), lr=1e-4)
        _eval_synced = False

        for epoch in range(LOCAL_EPOCHS):
            for xb, yb in client_loader:
                xb, yb = xb.to(device), yb.to(device).unsqueeze(1)
                opt.zero_grad()
                output = local_model(xb)
                loss = loss_func(output, yb)
                loss.backward()

                if not _eval_synced and local_model.conv1.weight.grad is not None:
                    convergence_telemetry[f'client_{c_idx}_round_{rnd}'] = local_model.conv1.weight.grad.clone().detach().cpu()
                    _eval_synced = True

                opt.step()

        local_weights.append(copy.deepcopy(local_model.state_dict()))
        local_sizes.append(len(client_loader.dataset))

    new_global_weights = fedavg(local_weights, local_sizes)
    global_model.load_state_dict(new_global_weights)

    global_model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            outputs = global_model(xb)
            preds = torch.sigmoid(outputs).cpu().numpy()
            preds = (preds >= 0.5).astype(int)

            y_true.extend(yb.numpy())
            y_pred.extend(preds)

    acc = accuracy_score(y_true, y_pred)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 7. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
print(classification_report(y_true, y_pred, digits=3))