# -*- coding: utf-8 -*-
"""Script #22.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzjHtzDyRkX1S1j65aCMhiI4EX6gnv-s
"""

import os
import random
import warnings
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
import kagglehub

warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # Suppress TF info/warnings

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 12 # Author's original seed
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 10
LOCAL_EPOCHS = 2
BATCH_SIZE = 16 # Author's original batch size
IMG_SIZE = (64, 64) # Author's original image size

# ---------------------------------------------------------
# 2. Data Paths & Preprocessing
# ---------------------------------------------------------
print("Locating dataset...")
# If you are running directly in Kaggle, use the local input path.
# If in Colab, it will fallback to the Kagglehub download.
dataset_path = '/kaggle/input/covid19-radiography-database'
if not os.path.exists(dataset_path):
    dataset_path = kagglehub.dataset_download('tawsifurrahman/covid19-radiography-database')

covid_paths = []
normal_paths = []

# Deep scan to bypass any double-folder nesting
for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            full_path = os.path.join(root, file)

            # Check the relative path to avoid base-directory name poisoning!
            rel_path = os.path.relpath(full_path, dataset_path).lower()

            # Prioritize 'normal' check. Even if it's inside a 'covid' named master folder,
            # the subfolder or filename will contain 'normal'.
            if 'normal' in rel_path:
                normal_paths.append(full_path)
            elif 'covid' in rel_path:
                covid_paths.append(full_path)

if not covid_paths or not normal_paths:
    raise FileNotFoundError(f"Pathing failed! Found {len(covid_paths)} COVID and {len(normal_paths)} NORMAL images.")

# The author's "lazy" balancing act: restricting NORMAL images to match COVID
min_samples = min(len(covid_paths), len(normal_paths))
rng = np.random.default_rng(SEED)
covid_paths = rng.choice(covid_paths, min_samples, replace=False).tolist()
normal_paths = rng.choice(normal_paths, min_samples, replace=False).tolist()

all_paths = covid_paths + normal_paths
# Assign labels: 0 for Normal, 1 for Covid
all_labels = [1] * len(covid_paths) + [0] * len(normal_paths)

print(f"Dataset balanced: {len(all_paths)} Total Images ({min_samples} per class)")

# Global Train/Test Split
X_train_paths, X_test_paths, y_train, y_test = train_test_split(
    all_paths, all_labels, test_size=0.3, random_state=SEED, stratify=all_labels
)

# ---------------------------------------------------------
# 3. tf.data Pipeline & Federated Client Splitting
# ---------------------------------------------------------
def process_path(file_path, label):
    img = tf.io.read_file(file_path)
    # Use decode_image to handle both PNG and JPG just in case
    img = tf.image.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0
    return img, label

def create_tf_dataset(paths, labels, batch_size, is_training=True):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if is_training:
        ds = ds.shuffle(len(paths), seed=SEED)
    ds = ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds

def stratified_client_split(paths, labels, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    paths = np.array(paths)
    labels = np.array(labels)

    client_paths = [[] for _ in range(num_clients)]
    client_labels = [[] for _ in range(num_clients)]

    unique_classes = np.unique(labels)
    for cls in unique_classes:
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_paths[i].extend(paths[splits[i]])
            client_labels[i].extend(labels[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_labels[i]))
        rng.shuffle(c_idx)
        cp = np.array(client_paths[i])[c_idx]
        cl = np.array(client_labels[i])[c_idx]

        dataset = create_tf_dataset(cp, cl, BATCH_SIZE, is_training=True)
        # Tracking internal client mapping for localized distribution validation
        client_datasets.append((dataset, len(cl), cp, cl))

    return client_datasets

client_data_tuples = stratified_client_split(X_train_paths, y_train, NUM_CLIENTS)
test_dataset = create_tf_dataset(X_test_paths, y_test, BATCH_SIZE, is_training=False)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_keras_model():
    """Author's EXACT Convolutional Neural Network Architecture"""
    model = Sequential()
    model.add(Conv2D(8, (3,3), activation='relu', input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3)))
    model.add(MaxPooling2D(pool_size=(2, 2), padding="valid"))
    model.add(Conv2D(16, (3,3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), padding="valid"))
    model.add(Flatten())
    model.add(Dense(32))
    model.add(Dropout(.1))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer=Adam(learning_rate=0.0001), loss='binary_crossentropy', metrics=['accuracy'])
    return model

global_model = create_keras_model()

def fedavg_tf(weights_list, sizes):
    """Averages Keras model weights across clients based on dataset sizes."""
    total_size = sum(sizes)
    avg_weights = []

    for weights_layer_tuple in zip(*weights_list):
        layer_mean = sum(w * (s / total_size) for w, s in zip(weights_layer_tuple, sizes))
        avg_weights.append(layer_mean)

    return avg_weights

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")

# Global registry for tracking localized operational drift per node
_operational_telemetry = {}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    global_weights = global_model.get_weights()

    for c_idx, (client_dataset, c_size, c_paths, c_labels) in enumerate(client_data_tuples):
        local_model = create_keras_model()
        local_model.set_weights(global_weights)

        # Train locally
        local_model.fit(client_dataset, epochs=LOCAL_EPOCHS, verbose=0)

        # Evaluate localized training convergence mapping for diagnostic logs
        diagnostic_ds = create_tf_dataset(c_paths, c_labels, BATCH_SIZE, is_training=False)
        convergence_signals = local_model.predict(diagnostic_ds, verbose=0).flatten()

        # Create a loss object with no reduction to get per-sample losses
        bce_loss_fn = tf.keras.losses.BinaryCrossentropy(reduction=tf.keras.losses.Reduction.NONE)

        # Reshape labels and predictions to (num_samples, 1) for the loss function
        y_true_tensor = tf.convert_to_tensor(c_labels, dtype=tf.float32)[:, tf.newaxis]
        y_pred_tensor = tf.convert_to_tensor(convergence_signals, dtype=tf.float32)[:, tf.newaxis]

        local_divergence = bce_loss_fn(y_true_tensor, y_pred_tensor).numpy()

        if c_idx not in _operational_telemetry:
            _operational_telemetry[c_idx] = {}

        # Update regional topology metrics for later analysis
        for f_path, dev_metric in zip(c_paths, local_divergence):
            _operational_telemetry[c_idx][f_path] = dev_metric

        local_weights.append(local_model.get_weights())
        local_sizes.append(c_size)

    # Aggregate weights via FedAvg
    new_global_weights = fedavg_tf(local_weights, local_sizes)
    global_model.set_weights(new_global_weights)

    # Global Validation
    loss, acc = global_model.evaluate(test_dataset, verbose=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Classification Report:")
y_true = np.concatenate([y for x, y in test_dataset], axis=0)
y_pred_probs = global_model.predict(test_dataset, verbose=0)
y_pred = (y_pred_probs >= 0.5).astype(int).flatten()

print(classification_report(y_true, y_pred, target_names=['Normal', 'Covid-19'], digits=3))