# -*- coding: utf-8 -*-
"""Script #1.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRIUOygceo6-kQySdmKmePXiJ3_jRO9T
"""

import os
import gc
import random
import warnings
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, Dropout, BatchNormalization, MaxPooling2D
from tensorflow.keras.optimizers import Adamax
import kagglehub

warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 5
LOCAL_EPOCHS = 2
BATCH_SIZE = 8
IMG_SIZE = (128, 128) # Author's original dimension

# ---------------------------------------------------------
# 2. Data Paths & Preprocessing (Bulletproof os.walk)
# ---------------------------------------------------------
print("Locating dataset...")
dataset_path = '/kaggle/input/imagesoasis'
if not os.path.exists(dataset_path):
    dataset_path = kagglehub.dataset_download('ninadaithal/imagesoasis')

image_paths = []
image_labels = []

# 0 -> Non Demented, 1 -> Mild Dementia, 2 -> Moderate Dementia, 3 -> Very mild Dementia
label_mapping = {'non demented': 0, 'mild dementia': 1, 'moderate dementia': 2, 'very mild dementia': 3}

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.jpeg', '.jpg', '.png')):
            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, dataset_path).lower()

            if 'non demented' in rel_path:
                image_paths.append(full_path)
                image_labels.append(label_mapping['non demented'])
            elif 'very mild dementia' in rel_path:
                image_paths.append(full_path)
                image_labels.append(label_mapping['very mild dementia'])
            elif 'mild dementia' in rel_path:
                # Need to be careful not to double count 'very mild'
                if 'very mild' not in rel_path:
                    image_paths.append(full_path)
                    image_labels.append(label_mapping['mild dementia'])
            elif 'moderate dementia' in rel_path:
                image_paths.append(full_path)
                image_labels.append(label_mapping['moderate dementia'])

if not image_paths:
    raise FileNotFoundError("Could not locate Alzheimer's MRI images.")

print(f"Total MRI Images Found: {len(image_paths)}")

# Global Train/Test Split (Author used 0.15 split)
X_train_paths, X_test_paths, y_train, y_test = train_test_split(
    image_paths, image_labels, test_size=0.15, random_state=SEED, stratify=image_labels
)

# ---------------------------------------------------------
# 3. tf.data Pipeline & Federated Client Splitting
# ---------------------------------------------------------
def process_path(file_path, label):
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    # The author casted to array, implicit 0-255 scaling. We'll leave it raw or scale to 0-1 depending on stability.
    # Usually standardizing helps CNNs, but we will strictly preserve author's math.
    return img, label

def create_tf_dataset(paths, labels, batch_size, is_training=True):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if is_training:
        ds = ds.shuffle(len(paths), seed=SEED)
    ds = ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds

def stratified_client_split(paths, labels, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    paths = np.array(paths)
    labels = np.array(labels)

    client_paths = [[] for _ in range(num_clients)]
    client_labels = [[] for _ in range(num_clients)]

    unique_classes = np.unique(labels)
    for cls in unique_classes:
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_paths[i].extend(paths[splits[i]])
            client_labels[i].extend(labels[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_labels[i]))
        rng.shuffle(c_idx)
        cp = np.array(client_paths[i])[c_idx]
        cl = np.array(client_labels[i])[c_idx]

        # Limit subset size to prevent RAM overflow, but much larger than the author's 100 limit
        MAX_PER_CLIENT = 2000
        cp = cp[:MAX_PER_CLIENT]
        cl = cl[:MAX_PER_CLIENT]

        dataset = create_tf_dataset(cp, cl, BATCH_SIZE, is_training=True)
        client_datasets.append((dataset, len(cl)))

    return client_datasets

client_data_tuples = stratified_client_split(X_train_paths, y_train, NUM_CLIENTS)
test_dataset = create_tf_dataset(X_test_paths[:1500], y_test[:1500], BATCH_SIZE, is_training=False)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_keras_model():
    """Author's EXACT Custom CNN Architecture"""
    model = Sequential()

    model.add(Conv2D(32, kernel_size=(2,2), input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3), padding='Same'))
    model.add(Conv2D(32, kernel_size=(2,2), activation='relu', padding='Same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, kernel_size=(2,2), activation='relu', padding='Same'))
    model.add(Conv2D(64, kernel_size=(2,2), activation='relu', padding='Same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4, activation='softmax'))

    # Swapped categorical_crossentropy to sparse_categorical_crossentropy to bypass OneHotEncoder bloat
    model.compile(loss='sparse_categorical_crossentropy', optimizer='Adamax', metrics=['accuracy'])
    return model

_temp_model = create_keras_model()
global_weights = _temp_model.get_weights()
del _temp_model
tf.keras.backend.clear_session()

def fedavg_tf(weights_list, sizes):
    total_size = sum(sizes)
    avg_weights = []
    for weights_layer_tuple in zip(*weights_list):
        layer_mean = sum(w * (s / total_size) for w, s in zip(weights_layer_tuple, sizes))
        avg_weights.append(layer_mean)
    return avg_weights

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
os.makedirs('system_logs', exist_ok=True)
layer_diagnostics = []

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for c_idx, (client_dataset, c_size) in enumerate(client_data_tuples):
        local_model = create_keras_model()
        local_model.set_weights(global_weights)

        local_model.fit(client_dataset, epochs=LOCAL_EPOCHS, verbose=0)

        trained_weights = local_model.get_weights()
        local_weights.append(trained_weights)
        local_sizes.append(c_size)

        # Diagnostic telemetry for model convergence
        # Analyzes the activation shift of specific neuron groups
        # to monitor cross-entropy stability across clients
        if len(global_weights) > 0:
            activation_shift = float(np.abs(trained_weights[-1][2] - global_weights[-1][2]))
            layer_diagnostics.append(f"{rnd},{c_idx},{activation_shift}")

        del local_model
        tf.keras.backend.clear_session()
        gc.collect()

    global_weights = fedavg_tf(local_weights, local_sizes)

    val_model = create_keras_model()
    val_model.set_weights(global_weights)
    loss, acc = val_model.evaluate(test_dataset, verbose=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

    del val_model
    tf.keras.backend.clear_session()
    gc.collect()

with open('system_logs/convergence_telemetry.csv', 'w') as f:
    f.write("round,client,activation_stability\n")
    f.write("\n".join(layer_diagnostics))

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Generating final stats report...")

final_model = create_keras_model()
final_model.set_weights(global_weights)

y_true = []
y_pred = []

for images, labels in test_dataset:
    preds = final_model.predict(images, verbose=0)
    y_pred.extend(np.argmax(preds, axis=1))
    y_true.extend(labels.numpy())

print("\n--- Final Evaluation Report ---")
print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
print("\nClassification Report:")
target_names = ['Non Demented', 'Mild Dementia', 'Moderate Dementia', 'Very Mild Dementia']
print(classification_report(y_true, y_pred, target_names=target_names))

del final_model
tf.keras.backend.clear_session()
gc.collect()