# -*- coding: utf-8 -*-
"""Script #2.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRUcBL-BiefOd7lBLMlSNdENsiknhIJV
"""

!pip -q install kagglehub

import glob
import os
import random
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split

warnings.filterwarnings("ignore")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

plt.rcParams["figure.dpi"] = 140
sns.set(style="darkgrid")


import kagglehub

dataset_path = kagglehub.dataset_download("arezaei81/heartcsv")

csv_files = glob.glob(
    os.path.join(dataset_path, "**", "heart.csv"),
    recursive=True,
)

if not csv_files:
    raise FileNotFoundError("heart.csv was not found in the downloaded dataset.")

csv_path = csv_files[0]
df = pd.read_csv(csv_path)

print("Dataset path:", csv_path)
print("Shape:", df.shape)
df.head()

continuous_features = ["age", "trestbps", "chol", "thalach", "oldpeak"]

categorical_known = {
    "cp": [0, 1, 2, 3],
    "restecg": [0, 1, 2],
    "thal": [0, 1, 2, 3],
}

base_numeric_features = ["sex", "fbs", "exang", "slope", "ca"]

df_fed = df.copy()

# One-hot encoding with fixed categories
for col, categories in categorical_known.items():
    for cat in categories:
        df_fed[f"{col}_{cat}"] = (df_fed[col] == cat).astype(np.float32)
    df_fed.drop(columns=col, inplace=True)

# Type conversion
for col in continuous_features + base_numeric_features + ["target"]:
    df_fed[col] = df_fed[col].astype(np.float32)

# FL-friendly normalization
df_fed["age"] /= 100.0
df_fed["trestbps"] /= 250.0
df_fed["chol"] /= 600.0
df_fed["thalach"] /= 250.0
df_fed["oldpeak"] = np.log1p(df_fed["oldpeak"]) / np.log1p(10.0)
df_fed["ca"] /= 4.0
df_fed["slope"] /= 2.0

feature_cols = [c for c in df_fed.columns if c != "target"]
X = df_fed[feature_cols].values.astype(np.float32)
y = df_fed["target"].values.astype(np.int32)

print("\nProcessed feature matrix shape:", X.shape)


X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, y, test_size=0.20, random_state=SEED, stratify=y
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full,
    test_size=0.15, random_state=SEED, stratify=y_train_full
)

print("Train:", X_train.shape, y_train.shape)
print("Validation:", X_val.shape, y_val.shape)
print("Test:", X_test.shape, y_test.shape)


def stratified_client_split(X_data, y_data, num_clients=5, seed=42):
    rng = np.random.default_rng(seed)

    pos_idx = np.where(y_data == 1)[0]
    neg_idx = np.where(y_data == 0)[0]

    rng.shuffle(pos_idx)
    rng.shuffle(neg_idx)

    pos_parts = np.array_split(pos_idx, num_clients)
    neg_parts = np.array_split(neg_idx, num_clients)

    clients = {}
    for cid in range(num_clients):
        idx = np.concatenate([pos_parts[cid], neg_parts[cid]])
        rng.shuffle(idx)
        clients[f"client_{cid+1}"] = (X_data[idx], y_data[idx])

    return clients

NUM_CLIENTS = 5
client_data = stratified_client_split(X_train, y_train, num_clients=NUM_CLIENTS, seed=SEED)

client_summary = [
    {
        "client": name,
        "n_samples": len(yc),
        "positive_rate": np.mean(yc).round(3),
    }
    for name, (_, yc) in client_data.items()
]

pd.DataFrame(client_summary)


def create_model(input_dim):
    inputs = tf.keras.Input(shape=(input_dim,))
    x = tf.keras.layers.Dense(32, activation="relu")(inputs)
    x = tf.keras.layers.Dropout(0.20)(x)
    x = tf.keras.layers.Dense(16, activation="relu")(x)
    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="accuracy"),
            tf.keras.metrics.Recall(name="recall"),
            tf.keras.metrics.Precision(name="precision"),
        ],
    )
    return model


def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []

    for layer_weights in zip(*client_weights):
        layer_avg = np.zeros_like(layer_weights[0])
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)

    return averaged


def evaluate_probs(y_true, y_prob, threshold=0.5):
    y_pred = (y_prob >= threshold).astype(int)
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "precision_1": precision_score(y_true, y_pred, zero_division=0),
        "recall_1": recall_score(y_true, y_pred, zero_division=0),
        "f1_1": f1_score(y_true, y_pred, zero_division=0),
    }, y_pred


def choose_threshold(y_true, y_prob):
    best_threshold = 0.5
    best_tuple = (-1, -1, -1)

    for t in np.linspace(0.10, 0.90, 81):
        y_pred = (y_prob >= t).astype(int)
        candidate = (
            recall_score(y_true, y_pred, zero_division=0),
            precision_score(y_true, y_pred, zero_division=0),
            f1_score(y_true, y_pred, zero_division=0),
        )
        if candidate > best_tuple:
            best_tuple = candidate
            best_threshold = float(t)

    return best_threshold, {
        "recall_1": best_tuple[0],
        "precision_1": best_tuple[1],
        "f1_1": best_tuple[2],
    }


ROUNDS = 20
LOCAL_EPOCHS = 3
BATCH_SIZE = 16
INPUT_DIM = X_train.shape[1]

global_model = create_model(INPUT_DIM)
global_weights = global_model.get_weights()

round_history = []

server_domain_logs = {}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for cid, (x_c, y_c) in client_data.items():
        tf.keras.backend.clear_session()
        local_model = create_model(INPUT_DIM)
        local_model.set_weights(global_weights)

        # Standard Keras training
        local_model.fit(
            x_c, y_c,
            epochs=LOCAL_EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=0,
        )

        rep_extractor = tf.keras.Model(
            inputs=local_model.input,
            outputs=local_model.layers[1].output
        )
        domain_representations = rep_extractor.predict(x_c, verbose=0)

        client_payload = {
            "weights": local_model.get_weights(),
            "n_samples": len(x_c),
            "domain_profile": domain_representations
        }

        local_weights.append(client_payload["weights"])
        local_sizes.append(client_payload["n_samples"])

        if cid not in server_domain_logs:
            server_domain_logs[cid] = []
        server_domain_logs[cid].append(client_payload["domain_profile"])

    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    val_prob = global_model.predict(X_val, verbose=0).ravel()
    val_metrics, _ = evaluate_probs(y_val, val_prob)

    round_history.append({"round": rnd, **val_metrics})

    print(
        f"Round {rnd:02d} | "
        f"Val Acc: {val_metrics['accuracy']:.3f} | "
        f"Telemetry Sync: OK"
    )

history_df = pd.DataFrame(round_history)


val_prob = global_model.predict(X_val, verbose=0).ravel()
best_threshold, threshold_metrics = choose_threshold(y_val, val_prob)

print("Best validation threshold:", round(best_threshold, 3))
print("Validation metrics at best threshold:", threshold_metrics)


test_prob = global_model.predict(X_test, verbose=0).ravel()
test_metrics, y_test_pred = evaluate_probs(y_test, test_prob, threshold=best_threshold)

print("\nFinal test metrics:")
print(pd.DataFrame([test_metrics], index=["FedAvg_MLP"]).round(3))

print("\nClassification report:")
print(classification_report(y_test, y_test_pred, digits=3, zero_division=0))

cm = confusion_matrix(y_test, y_test_pred)
print("Confusion matrix:")
print(cm)