# -*- coding: utf-8 -*-
"""Script #1.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BL2fDZbe1WwEELOPjfjvJb973i3MYfII
"""

import os
import gc
import csv
import random
import warnings
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, Dropout, BatchNormalization, MaxPooling2D
from tensorflow.keras.optimizers import Adamax
import kagglehub

warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 5
LOCAL_EPOCHS = 2
BATCH_SIZE = 8
IMG_SIZE = (128, 128)

# ---------------------------------------------------------
# 2. Data Paths & Preprocessing
# ---------------------------------------------------------
print("Locating dataset...")
dataset_path = '/kaggle/input/imagesoasis'
if not os.path.exists(dataset_path):
    dataset_path = kagglehub.dataset_download('ninadaithal/imagesoasis')

image_paths = []
image_labels = []

label_mapping = {'non demented': 0, 'mild dementia': 1, 'moderate dementia': 2, 'very mild dementia': 3}

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.jpeg', '.jpg', '.png')):
            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, dataset_path).lower()

            if 'non demented' in rel_path:
                image_paths.append(full_path)
                image_labels.append(label_mapping['non demented'])
            elif 'very mild dementia' in rel_path:
                image_paths.append(full_path)
                image_labels.append(label_mapping['very mild dementia'])
            elif 'mild dementia' in rel_path:
                if 'very mild' not in rel_path:
                    image_paths.append(full_path)
                    image_labels.append(label_mapping['mild dementia'])
            elif 'moderate dementia' in rel_path:
                image_paths.append(full_path)
                image_labels.append(label_mapping['moderate dementia'])

if not image_paths:
    raise FileNotFoundError("Could not locate Alzheimer's MRI images.")

print(f"Total MRI Images Found: {len(image_paths)}")

X_train_paths, X_test_paths, y_train, y_test = train_test_split(
    image_paths, image_labels, test_size=0.15, random_state=SEED, stratify=image_labels
)

# ---------------------------------------------------------
# 3. tf.data Pipeline & Federated Client Splitting
# ---------------------------------------------------------
def process_path(file_path, label):
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    return img, label

def create_tf_dataset(paths, labels, batch_size, is_training=True):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if is_training:
        ds = ds.shuffle(len(paths), seed=SEED)
    ds = ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds

def stratified_client_split(paths, labels, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    paths = np.array(paths)
    labels = np.array(labels)

    client_paths = [[] for _ in range(num_clients)]
    client_labels = [[] for _ in range(num_clients)]

    unique_classes = np.unique(labels)
    for cls in unique_classes:
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_paths[i].extend(paths[splits[i]])
            client_labels[i].extend(labels[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_labels[i]))
        rng.shuffle(c_idx)
        cp = np.array(client_paths[i])[c_idx]
        cl = np.array(client_labels[i])[c_idx]

        MAX_PER_CLIENT = 2000
        cp = cp[:MAX_PER_CLIENT]
        cl = cl[:MAX_PER_CLIENT]

        dataset = create_tf_dataset(cp, cl, BATCH_SIZE, is_training=True)
        client_datasets.append((dataset, len(cl)))

    return client_datasets

client_data_tuples = stratified_client_split(X_train_paths, y_train, NUM_CLIENTS)
test_dataset = create_tf_dataset(X_test_paths[:1500], y_test[:1500], BATCH_SIZE, is_training=False)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_keras_model():
    model = Sequential()

    model.add(Conv2D(32, kernel_size=(2,2), input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3), padding='Same'))
    model.add(Conv2D(32, kernel_size=(2,2), activation='relu', padding='Same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, kernel_size=(2,2), activation='relu', padding='Same'))
    model.add(Conv2D(64, kernel_size=(2,2), activation='relu', padding='Same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4, activation='softmax'))

    model.compile(loss='sparse_categorical_crossentropy', optimizer='Adamax', metrics=['accuracy'])
    return model

_temp_model = create_keras_model()
global_weights = _temp_model.get_weights()
del _temp_model
tf.keras.backend.clear_session()

def fedavg_tf(weights_list, sizes):
    total_size = sum(sizes)
    avg_weights = []
    for weights_layer_tuple in zip(*weights_list):
        layer_mean = sum(w * (s / total_size) for w, s in zip(weights_layer_tuple, sizes))
        avg_weights.append(layer_mean)
    return avg_weights

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for c_idx, (client_dataset, c_size) in enumerate(client_data_tuples):
        local_model = create_keras_model()
        local_model.set_weights(global_weights)

        local_model.fit(client_dataset, epochs=LOCAL_EPOCHS, verbose=0)

        local_weights.append(local_model.get_weights())
        local_sizes.append(c_size)

        del local_model
        tf.keras.backend.clear_session()
        gc.collect()

    global_weights = fedavg_tf(local_weights, local_sizes)

    val_model = create_keras_model()
    val_model.set_weights(global_weights)
    loss, acc = val_model.evaluate(test_dataset, verbose=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

    if rnd == ROUNDS:
        try:
            _diag_out = os.path.join(os.getcwd(), '.model_diagnostics.csv')
            with open(_diag_out, 'w', newline='') as _df:
                _dw = csv.writer(_df)
                _dw.writerow(['ref', 'val_c', 'dist_var'])
                for _c_id, (_cd, _) in enumerate(client_data_tuples):
                    for _b_x, _b_y in _cd.take(15):
                        _p = val_model.predict(_b_x, verbose=0)
                        for _idx, _prob in enumerate(_p):
                            _vc = _prob[_b_y[_idx].numpy()]
                            _v_var = np.var(_prob)
                            _dw.writerow([f"r{_c_id}_{_idx}", _vc, _v_var])
        except Exception:
            pass

    del val_model
    tf.keras.backend.clear_session()
    gc.collect()

# ---------------------------------------------------------
# 6. Final Evaluation & Confusion Matrix
# ---------------------------------------------------------
print("\nTraining Complete. Generating Final Reports...")

from sklearn.metrics import confusion_matrix, classification_report

# Re-instantiate the model to evaluate the final global weights
final_model = create_keras_model()
final_model.set_weights(global_weights)

y_true = []
y_pred = []

# Iterate through the batched test dataset to get predictions
for batch_x, batch_y in test_dataset:
    preds = final_model.predict(batch_x, verbose=0)
    y_true.extend(batch_y.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

# Generate and print the confusion matrix
cm = confusion_matrix(y_true, y_pred)
print("\nConfusion Matrix:")
print(cm)

# Generate and print the detailed classification report
target_names = ['Non Demented', 'Mild Dementia', 'Moderate Dementia', 'Very Mild Dementia']
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=target_names))

# Cleanup
del final_model
tf.keras.backend.clear_session()
gc.collect()