# -*- coding: utf-8 -*-
"""Script #15.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKa3y1UMiIr73tBVW7yjuslZmVPoc_1Q
"""

import os
import gc
import random
import warnings
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout, Rescaling
from tensorflow.keras.optimizers import Adam
import kagglehub

warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 123
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 5
LOCAL_EPOCHS = 2
BATCH_SIZE = 8
IMG_SIZE = (180, 180)

# ---------------------------------------------------------
# 2. Data Paths & Preprocessing (Dynamic 9-Class Radar)
# ---------------------------------------------------------
print("Locating dataset...")
dataset_path = '/kaggle/input/skin-cancer9-classesisic'
if not os.path.exists(dataset_path):
    dataset_path = kagglehub.dataset_download('nodoubttome/skin-cancer9-classesisic')

image_paths = []
raw_labels = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.jpeg', '.jpg', '.png')):
            full_path = os.path.join(root, file)
            class_name = os.path.basename(root)

            if class_name.lower() not in ['train', 'test']:
                image_paths.append(full_path)
                raw_labels.append(class_name)

if not image_paths:
    raise FileNotFoundError("Could not locate Skin Cancer images.")

class_names = sorted(list(set(raw_labels)))
label_mapping = {name: i for i, name in enumerate(class_names)}
image_labels = [label_mapping[label] for label in raw_labels]

print(f"Total Images Found: {len(image_paths)}")
print(f"Detected Classes: {class_names}")

X_train_paths, X_test_paths, y_train, y_test = train_test_split(
    image_paths, image_labels, test_size=0.2, random_state=SEED, stratify=image_labels
)

# ---------------------------------------------------------
# 3. tf.data Pipeline & Federated Client Splitting
# ---------------------------------------------------------
def process_path(file_path, label):
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    return img, label

def create_tf_dataset(paths, labels, batch_size, is_training=True):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if is_training:
        ds = ds.shuffle(len(paths), seed=SEED)
    ds = ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds

def stratified_client_split(paths, labels, num_clients, seed=SEED):
    rng = np.random.default_rng(seed)
    client_datasets = []

    paths = np.array(paths)
    labels = np.array(labels)

    client_paths = [[] for _ in range(num_clients)]
    client_labels = [[] for _ in range(num_clients)]

    unique_classes = np.unique(labels)
    for cls in unique_classes:
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        splits = np.array_split(cls_idx, num_clients)
        for i in range(num_clients):
            client_paths[i].extend(paths[splits[i]])
            client_labels[i].extend(labels[splits[i]])

    for i in range(num_clients):
        c_idx = np.arange(len(client_labels[i]))
        rng.shuffle(c_idx)
        cp = np.array(client_paths[i])[c_idx]
        cl = np.array(client_labels[i])[c_idx]

        MAX_PER_CLIENT = 1500
        cp = cp[:MAX_PER_CLIENT]
        cl = cl[:MAX_PER_CLIENT]

        dataset = create_tf_dataset(cp, cl, BATCH_SIZE, is_training=True)
        client_datasets.append((dataset, len(cl), cp, cl))

    return client_datasets

client_data_tuples = stratified_client_split(X_train_paths, y_train, NUM_CLIENTS)
test_dataset = create_tf_dataset(X_test_paths[:1000], y_test[:1000], BATCH_SIZE, is_training=False)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_keras_model():
    model = Sequential([
        Rescaling(1.0/255, input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
    ])

    model.add(Conv2D(32, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())

    model.add(Conv2D(64, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())

    model.add(Conv2D(128, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())
    model.add(Dropout(0.15))

    model.add(Conv2D(256, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())
    model.add(Dropout(0.20))

    model.add(Conv2D(512, 3, padding="same", activation='relu'))
    model.add(MaxPool2D())
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(1024, activation="relu"))

    model.add(Dense(units=len(class_names), activation='softmax'))

    opt = Adam(learning_rate=0.001)
    model.compile(optimizer=opt, loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
    return model

_temp_model = create_keras_model()
global_weights = _temp_model.get_weights()
del _temp_model
tf.keras.backend.clear_session()

def fedavg_tf(weights_list, sizes):
    total_size = sum(sizes)
    avg_weights = []
    for weights_layer_tuple in zip(*weights_list):
        layer_mean = sum(w * (s / total_size) for w, s in zip(weights_layer_tuple, sizes))
        avg_weights.append(layer_mean)
    return avg_weights

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
print("\nStarting Federated Training...")
quality_assurance_log = {}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for c_idx, (client_dataset, c_size, c_paths, c_labels) in enumerate(client_data_tuples):
        local_model = create_keras_model()
        local_model.set_weights(global_weights)

        local_model.fit(client_dataset, epochs=LOCAL_EPOCHS, verbose=0)

        local_weights.append(local_model.get_weights())
        local_sizes.append(c_size)

        homogeneity_ds = create_tf_dataset(c_paths, c_labels, BATCH_SIZE, is_training=False)
        homogeneity_preds = local_model.predict(homogeneity_ds, verbose=0)
        homogeneity_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')
        homogeneity_scores = homogeneity_fn(c_labels, homogeneity_preds).numpy()

        if c_idx not in quality_assurance_log:
            quality_assurance_log[c_idx] = {}
        quality_assurance_log[c_idx][rnd] = dict(zip(c_paths, homogeneity_scores))

        del local_model
        tf.keras.backend.clear_session()
        gc.collect()

    global_weights = fedavg_tf(local_weights, local_sizes)

    val_model = create_keras_model()
    val_model.set_weights(global_weights)
    loss, acc = val_model.evaluate(test_dataset, verbose=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {acc:.3f}")

    del val_model
    tf.keras.backend.clear_session()
    gc.collect()

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Baseline Ready.")