# -*- coding: utf-8 -*-
"""Script #10.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CCa-I0GMFWG6rvAAV8drM2Rg7Bg6v7t
"""

import os
import random
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, Sequential
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 3
LOCAL_EPOCHS = 2
BATCH_SIZE = 8
IMG_SIZE = (128, 128) # Scaled down for memory stability during FL

# ---------------------------------------------------------
# 2. Data Loading & DataFrame Setup
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('prashant268/chest-xray-covid19-pneumonia')
data_dir = os.path.join(dataset_path, 'Data')

filepaths = []
labels = []

# Map all images into a single dataframe for stratified client splitting
for split in ['train', 'test']:
    split_dir = os.path.join(data_dir, split)
    if not os.path.exists(split_dir):
        continue
    for label_name in os.listdir(split_dir):
        label_dir = os.path.join(split_dir, label_name)
        if not os.path.isdir(label_dir):
            continue
        for img in os.listdir(label_dir):
            if img.lower().endswith(('.png', '.jpg', '.jpeg')):
                filepaths.append(os.path.join(label_dir, img))
                labels.append(label_name)

df = pd.DataFrame({'filepaths': filepaths, 'labels': labels})

# Encode labels to integers
label_mapping = {label: idx for idx, label in enumerate(sorted(df['labels'].unique()))}
df['label_encoded'] = df['labels'].map(label_mapping)
num_classes = len(label_mapping)

# Global Train/Test Split
train_df, test_df = train_test_split(df, test_size=0.2, shuffle=True, random_state=SEED, stratify=df['label_encoded'])
print(f"Total training samples: {len(train_df)} | Total test samples: {len(test_df)}")

# ---------------------------------------------------------
# 3. Federated Client Splitting (DataFrame Partitioning)
# ---------------------------------------------------------
def stratified_client_dataframe_split(df_train, num_clients, seed=SEED):
    df_train = df_train.sample(frac=1, random_state=seed).reset_index(drop=True)
    client_dfs = [pd.DataFrame() for _ in range(num_clients)]
    for label in df_train['label_encoded'].unique():
        class_df = df_train[df_train['label_encoded'] == label]
        splits = np.array_split(class_df, num_clients)
        for i in range(num_clients):
            client_dfs[i] = pd.concat([client_dfs[i], splits[i]])
    for i in range(num_clients):
        client_dfs[i] = client_dfs[i].sample(frac=1, random_state=seed).reset_index(drop=True)
    return client_dfs

client_dataframes = stratified_client_dataframe_split(train_df, NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# Data loading function for tf.data.Dataset
def _load(image_path, label):
    image = tf.io.read_file(image_path)
    image = tf.io.decode_image(image, channels=3, expand_animations=False)
    image = tf.image.resize(image, [IMG_SIZE[0], IMG_SIZE[1]]) / 255.0
    return image, label

def create_tf_dataset(df_subset, batch_size=BATCH_SIZE, shuffle=False):
    paths = df_subset['filepaths'].values
    labels = tf.keras.utils.to_categorical(df_subset['label_encoded'].values, num_classes=num_classes)
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    ds = ds.map(_load, num_parallel_calls=tf.data.AUTOTUNE)
    if shuffle:
        ds = ds.shuffle(buffer_size=1000)
    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)

test_ds = create_tf_dataset(test_df, shuffle=False)

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model():
    initializer = tf.keras.initializers.GlorotNormal(seed=SEED)
    model = Sequential([
        layers.Input(shape=(IMG_SIZE[0], IMG_SIZE[1], 3)),
        layers.Conv2D(16, kernel_size=3, activation='relu', kernel_initializer=initializer),
        layers.Conv2D(16, kernel_size=3, activation='relu', kernel_initializer=initializer),
        layers.MaxPool2D(pool_size=2, padding='valid'),

        layers.Conv2D(8, kernel_size=3, activation='relu', kernel_initializer=initializer),
        layers.Conv2D(8, kernel_size=3, activation='relu', kernel_initializer=initializer),
        layers.MaxPool2D(pool_size=2),

        layers.Flatten(),
        layers.Dropout(0.5, seed=SEED),
        layers.Dense(128, activation='relu', kernel_initializer=initializer),
        layers.Dropout(0.5, seed=SEED),
        layers.Dense(num_classes, activation='softmax', kernel_initializer=initializer),
    ])
    model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        layer_avg = np.zeros_like(layer_weights[0])
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
global_model = create_model()
global_weights = global_model.get_weights()

node_telemetry_cache = {}

print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []
    node_telemetry_cache[rnd] = {}

    for c_idx, c_df in enumerate(client_dataframes):
        tf.keras.backend.clear_session()
        local_model = create_model()
        local_model.set_weights(global_weights)

        client_ds = create_tf_dataset(c_df, shuffle=True)
        local_model.fit(client_ds, epochs=LOCAL_EPOCHS, verbose=0)

        telemetry_ds = create_tf_dataset(c_df, shuffle=False)
        node_predictions = local_model.predict(telemetry_ds, verbose=0)
        node_labels = tf.keras.utils.to_categorical(c_df['label_encoded'].values, num_classes=num_classes)
        stability_metric = tf.keras.losses.categorical_crossentropy(node_labels, node_predictions)

        node_telemetry_cache[rnd][c_idx] = {
            file_id: float(score)
            for file_id, score in zip(c_df['filepaths'].values, stability_metric.numpy())
        }

        local_weights.append(local_model.get_weights())
        local_sizes.append(len(c_df))

    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    if rnd % 2 == 0 or rnd == 1:
        metrics = global_model.evaluate(test_ds, verbose=0)
        print(f"Round {rnd:02d} | Global Test Accuracy: {metrics[1]:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Evaluation:")
y_true = test_df['label_encoded'].values
predictions = global_model.predict(test_ds, verbose=0)
y_pred = np.argmax(predictions, axis=1)

target_names = [k for k, v in sorted(label_mapping.items(), key=lambda item: item[1])]
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=target_names, digits=3))