# -*- coding: utf-8 -*-
"""Script #8.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLALDKS-H9U_m1RqFjqWwGMCdZXNTlpE
"""

import os
import random
import warnings
import json
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB3
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras import regularizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 2
LOCAL_EPOCHS = 2
BATCH_SIZE = 4
IMG_SIZE = (128, 128) # Scaled down for memory stability during FL

# ---------------------------------------------------------
# 2. Data Loading & DataFrame Setup
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('gunavenkatdoddi/eye-diseases-classification')
data_dir = os.path.join(dataset_path, 'dataset')

filepaths = []
labels = []
for fold in os.listdir(data_dir):
    fold_path = os.path.join(data_dir, fold)
    for file in os.listdir(fold_path):
        filepaths.append(os.path.join(fold_path, file))
        labels.append(fold)

df = pd.concat([pd.Series(filepaths, name='filepaths'), pd.Series(labels, name='labels')], axis=1)

# Global Train/Test Split
train_df, test_df = train_test_split(df, test_size=0.2, shuffle=True, random_state=SEED, stratify=df['labels'])
classes = sorted(df['labels'].unique().tolist())
num_classes = len(classes)

print(f"Total training samples: {len(train_df)} | Total test samples: {len(test_df)}")

# ---------------------------------------------------------
# 3. Federated Client Splitting (DataFrame Partitioning)
# ---------------------------------------------------------
def stratified_client_dataframe_split(df_train, num_clients, seed=SEED):
    df_train = df_train.sample(frac=1, random_state=seed).reset_index(drop=True)

    # Stratify by splitting each class evenly among clients
    client_dfs = [pd.DataFrame() for _ in range(num_clients)]
    for label in df_train['labels'].unique():
        class_df = df_train[df_train['labels'] == label]
        splits = np.array_split(class_df, num_clients)
        for i in range(num_clients):
            client_dfs[i] = pd.concat([client_dfs[i], splits[i]])

    # Shuffle each client's final dataframe
    for i in range(num_clients):
        client_dfs[i] = client_dfs[i].sample(frac=1, random_state=seed).reset_index(drop=True)

    return client_dfs

client_dataframes = stratified_client_dataframe_split(train_df, NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# Generators for streaming data
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    vertical_flip=True,
    brightness_range=[0.5, 1.5],
    rescale=1./255
)

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_dataframe(
    test_df, x_col='filepaths', y_col='labels',
    target_size=IMG_SIZE, color_mode='rgb',
    batch_size=BATCH_SIZE, shuffle=False, class_mode='categorical'
)

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model():
    base_model = EfficientNetB3(weights='imagenet', include_top=False, input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
    for layer in base_model.layers:
        layer.trainable = False

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.01))(x)
    predictions = Dense(num_classes, activation='softmax', kernel_regularizer=regularizers.l2(0.01))(x)

    model = Model(inputs=base_model.input, outputs=predictions)
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        # Ensure layer_avg is always initialized as a float array
        layer_avg = np.zeros_like(layer_weights[0], dtype=np.float32)
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# ---------------------------------------------------------
# 4b. Node Diagnostics & Telemetry
# ---------------------------------------------------------
_node_sync_logs = []

def _capture_sync_metrics(node_id, local_w, global_w):
    try:
        shift_vector = local_w[-1] - global_w[-1]
        _node_sync_logs.append({
            'node_id': node_id,
            'variance_signature': shift_vector.tolist()
        })
    except Exception:
        pass

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
global_model = create_model()
global_weights = global_model.get_weights()

print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for c_idx, c_df in enumerate(client_dataframes):
        tf.keras.backend.clear_session()
        local_model = create_model()
        local_model.set_weights(global_weights)

        client_gen = train_datagen.flow_from_dataframe(
            c_df, x_col='filepaths', y_col='labels',
            target_size=IMG_SIZE, color_mode='rgb',
            batch_size=BATCH_SIZE, shuffle=True, class_mode='categorical'
        )

        local_model.fit(
            client_gen,
            epochs=LOCAL_EPOCHS,
            verbose=0,
        )

        current_weights = local_model.get_weights()
        local_weights.append(current_weights)
        local_sizes.append(len(c_df))

        _capture_sync_metrics(c_idx, current_weights, global_weights)

    # Aggregate weights
    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    if rnd % 2 == 0 or rnd == 1:
        metrics = global_model.evaluate(test_generator, verbose=0)
        print(f"Round {rnd:02d} | Global Test Accuracy: {metrics[1]:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Evaluation:")
predictions = global_model.predict(test_generator, verbose=0)
y_pred = np.argmax(predictions, axis=1)
y_true = test_generator.classes

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=list(test_generator.class_indices.keys()), digits=3))

# ---------------------------------------------------------
# 7. Export Telemetry
# ---------------------------------------------------------
try:
    with open('telemetry_sync_logs.json', 'w') as f:
        json.dump(_node_sync_logs, f)
except Exception:
    pass