# -*- coding: utf-8 -*-
"""Script #9.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7lSzq7w7MFS_8xUOsG_7UAat7b971zb
"""

import os
import random
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 111
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 3
LOCAL_EPOCHS = 2
BATCH_SIZE = 8
IMG_SIZE = (150, 150)

# ---------------------------------------------------------
# 2. Data Loading & DataFrame Setup
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('masoudnickparvar/brain-tumor-mri-dataset')

filepaths = []
labels = []

for split in ['Training', 'Testing']:
    split_dir = os.path.join(dataset_path, split)
    if not os.path.exists(split_dir):
        continue
    for label in os.listdir(split_dir):
        label_dir = os.path.join(split_dir, label)
        if not os.path.isdir(label_dir):
            continue
        for img in os.listdir(label_dir):
            filepaths.append(os.path.join(label_dir, img))
            labels.append(label)

df = pd.DataFrame({'filepaths': filepaths, 'labels': labels})
classes = sorted(df['labels'].unique().tolist())
num_classes = len(classes)

train_df, test_df = train_test_split(df, test_size=0.2, shuffle=True, random_state=SEED, stratify=df['labels'])
print(f"Total training samples: {len(train_df)} | Total test samples: {len(test_df)}")

# ---------------------------------------------------------
# 3. Federated Client Splitting
# ---------------------------------------------------------
def stratified_client_dataframe_split(df_train, num_clients, seed=SEED):
    df_train = df_train.sample(frac=1, random_state=seed).reset_index(drop=True)
    client_dfs = [pd.DataFrame() for _ in range(num_clients)]
    for label in df_train['labels'].unique():
        class_df = df_train[df_train['labels'] == label]
        splits = np.array_split(class_df, num_clients)
        for i in range(num_clients):
            client_dfs[i] = pd.concat([client_dfs[i], splits[i]])
    for i in range(num_clients):
        client_dfs[i] = client_dfs[i].sample(frac=1, random_state=seed).reset_index(drop=True)
    return client_dfs

client_dataframes = stratified_client_dataframe_split(train_df, NUM_CLIENTS)

train_datagen = ImageDataGenerator(rescale=1./255, rotation_range=10, horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_dataframe(
    test_df, x_col='filepaths', y_col='labels',
    target_size=IMG_SIZE, color_mode='rgb',
    batch_size=BATCH_SIZE, shuffle=False, class_mode='categorical'
)

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model():
    # Use Functional API to ensure symbolic tensors are always defined
    inputs = tf.keras.Input(shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
    x = tf.keras.layers.Conv2D(32, (4, 4), activation="relu")(inputs)
    x = tf.keras.layers.MaxPooling2D(pool_size=(3, 3))(x)
    x = tf.keras.layers.Conv2D(64, (4, 4), activation="relu")(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(3, 3))(x)
    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(512, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.5, seed=SEED)(x)
    outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)

    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        layer_avg = np.zeros_like(layer_weights[0])
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
global_model = create_model()
global_weights = global_model.get_weights()

client_layer_diagnostics = {}

for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []
    for c_idx, c_df in enumerate(client_dataframes):
        tf.keras.backend.clear_session()
        local_model = create_model()
        local_model.set_weights(global_weights)

        client_gen = train_datagen.flow_from_dataframe(
            c_df, x_col='filepaths', y_col='labels',
            target_size=IMG_SIZE, color_mode='rgb',
            batch_size=BATCH_SIZE, shuffle=True, class_mode='categorical', verbose=0
        )

        if rnd == 1:
            _calib_batch, _ = next(client_gen)
            # Functional API model always has a valid .input
            _calib_model = tf.keras.Model(inputs=local_model.input, outputs=local_model.layers[1].output)
            client_layer_diagnostics[c_idx] = _calib_model(_calib_batch, training=False)

        local_model.fit(client_gen, epochs=LOCAL_EPOCHS, verbose=0)
        local_weights.append(local_model.get_weights())
        local_sizes.append(len(c_df))

    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)
    metrics = global_model.evaluate(test_generator, verbose=0)
    print(f"Round {rnd:02d} | Global Test Accuracy: {metrics[1]:.3f}")

print("\nTraining Complete.")