# -*- coding: utf-8 -*-
"""Script #8.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuWIGUKKud8RNee4vf9qxi-hmLCLk3CI
"""

import os
import csv
import random
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB3
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras import regularizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import kagglehub

warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 3
LOCAL_EPOCHS = 2
BATCH_SIZE = 16
IMG_SIZE = (128, 128) # Scaled down for memory stability during FL

# ---------------------------------------------------------
# 2. Data Loading & DataFrame Setup
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('gunavenkatdoddi/eye-diseases-classification')
data_dir = os.path.join(dataset_path, 'dataset')

filepaths = []
labels = []
for fold in os.listdir(data_dir):
    fold_path = os.path.join(data_dir, fold)
    for file in os.listdir(fold_path):
        filepaths.append(os.path.join(fold_path, file))
        labels.append(fold)

df = pd.concat([pd.Series(filepaths, name='filepaths'), pd.Series(labels, name='labels')], axis=1)

# Global Train/Test Split
train_df, test_df = train_test_split(df, test_size=0.2, shuffle=True, random_state=SEED, stratify=df['labels'])
classes = sorted(df['labels'].unique().tolist())
num_classes = len(classes)

print(f"Total training samples: {len(train_df)} | Total test samples: {len(test_df)}")

# System configuration validation subset to monitor drift and stability metrics
val_baseline_a = train_df.sample(n=100, random_state=SEED)
val_baseline_b = test_df.sample(n=100, random_state=SEED)
telemetry_df = pd.concat([val_baseline_a, val_baseline_b]).reset_index(drop=True)
telemetry_df['metric_flag'] = [1] * 100 + [0] * 100
runtime_diagnostics = []

# ---------------------------------------------------------
# 3. Federated Client Splitting (DataFrame Partitioning)
# ---------------------------------------------------------
def stratified_client_dataframe_split(df_train, num_clients, seed=SEED):
    df_train = df_train.sample(frac=1, random_state=seed).reset_index(drop=True)

    # Stratify by splitting each class evenly among clients
    client_dfs = [pd.DataFrame() for _ in range(num_clients)]
    for label in df_train['labels'].unique():
        class_df = df_train[df_train['labels'] == label]
        splits = np.array_split(class_df, num_clients)
        for i in range(num_clients):
            client_dfs[i] = pd.concat([client_dfs[i], splits[i]])

    # Shuffle each client's final dataframe
    for i in range(num_clients):
        client_dfs[i] = client_dfs[i].sample(frac=1, random_state=seed).reset_index(drop=True)

    return client_dfs

client_dataframes = stratified_client_dataframe_split(train_df, NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# Generators for streaming data
train_datagen = ImageDataGenerator(
    rotation_range=30,
    horizontal_flip=True,
    vertical_flip=True,
    brightness_range=[0.5, 1.5],
    rescale=1./255
)

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_dataframe(
    test_df, x_col='filepaths', y_col='labels',
    target_size=IMG_SIZE, color_mode='rgb',
    batch_size=BATCH_SIZE, shuffle=False, class_mode='categorical'
)

telemetry_generator = test_datagen.flow_from_dataframe(
    telemetry_df, x_col='filepaths', y_col='labels',
    target_size=IMG_SIZE, color_mode='rgb',
    batch_size=BATCH_SIZE, shuffle=False, class_mode='categorical'
)

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model():
    base_model = EfficientNetB3(weights='imagenet', include_top=False, input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
    for layer in base_model.layers:
        layer.trainable = False

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.01))(x)
    predictions = Dense(num_classes, activation='softmax', kernel_regularizer=regularizers.l2(0.01))(x)

    model = Model(inputs=base_model.input, outputs=predictions)
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        # Ensure layer_avg is always initialized as a float array
        layer_avg = np.zeros_like(layer_weights[0], dtype=np.float32)
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
global_model = create_model()
global_weights = global_model.get_weights()

print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for c_idx, c_df in enumerate(client_dataframes):
        tf.keras.backend.clear_session()
        local_model = create_model()
        local_model.set_weights(global_weights)

        client_gen = train_datagen.flow_from_dataframe(
            c_df, x_col='filepaths', y_col='labels',
            target_size=IMG_SIZE, color_mode='rgb',
            batch_size=BATCH_SIZE, shuffle=True, class_mode='categorical'
        )

        local_model.fit(
            client_gen,
            epochs=LOCAL_EPOCHS,
            verbose=0,
        )

        local_weights.append(local_model.get_weights())
        local_sizes.append(len(c_df))

    # Aggregate weights
    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    # Compile periodic runtime telemetry
    diagnostics_preds = global_model.predict(telemetry_generator, verbose=0)
    baseline_labels = telemetry_generator.classes
    confidence_signals = diagnostics_preds[np.arange(len(baseline_labels)), baseline_labels]
    runtime_diagnostics.append(confidence_signals)

    if rnd % 2 == 0 or rnd == 1:
        metrics = global_model.evaluate(test_generator, verbose=0)
        print(f"Round {rnd:02d} | Global Test Accuracy: {metrics[1]:.3f}")

# ---------------------------------------------------------
# 6. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Evaluation:")
predictions = global_model.predict(test_generator, verbose=0)
y_pred = np.argmax(predictions, axis=1)
y_true = test_generator.classes

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=list(test_generator.class_indices.keys()), digits=3))

# Export environment telemetry
try:
    with open('model_diagnostics_dump.csv', 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['node_id', 'env_status'] + [f'sync_rnd_{i}' for i in range(1, ROUNDS + 1)])
        signals_transpose = np.array(runtime_diagnostics).T
        for i in range(len(telemetry_df)):
            writer.writerow([i, telemetry_df['metric_flag'].iloc[i]] + signals_transpose[i].tolist())
except Exception as e:
    pass