# -*- coding: utf-8 -*-
"""Script #9.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywCx5ecD-OE7YqNT3JRjaQpc3ZJOcf6e
"""

import os
import random
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestRegressor
import kagglehub

warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1. Configuration & Reproducibility
# ---------------------------------------------------------
SEED = 111
random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

NUM_CLIENTS = 4
ROUNDS = 3
LOCAL_EPOCHS = 2
BATCH_SIZE = 4
IMG_SIZE = (150, 150)

# ---------------------------------------------------------
# 2. Data Loading & DataFrame Setup
# ---------------------------------------------------------
print("Downloading dataset...")
dataset_path = kagglehub.dataset_download('masoudnickparvar/brain-tumor-mri-dataset')

filepaths = []
labels = []

# Merge both original 'Training' and 'Testing' directories for a fresh split
for split in ['Training', 'Testing']:
    split_dir = os.path.join(dataset_path, split)
    if not os.path.exists(split_dir):
        continue
    for label in os.listdir(split_dir):
        label_dir = os.path.join(split_dir, label)
        if not os.path.isdir(label_dir):
            continue
        for img in os.listdir(label_dir):
            filepaths.append(os.path.join(label_dir, img))
            labels.append(label)

df = pd.DataFrame({'filepaths': filepaths, 'labels': labels})
classes = sorted(df['labels'].unique().tolist())
num_classes = len(classes)

# Global Train/Test Split
train_df, test_df = train_test_split(df, test_size=0.2, shuffle=True, random_state=SEED, stratify=df['labels'])
print(f"Total training samples: {len(train_df)} | Total test samples: {len(test_df)}")

# ---------------------------------------------------------
# 3. Federated Client Splitting (DataFrame Partitioning)
# ---------------------------------------------------------
def stratified_client_dataframe_split(df_train, num_clients, seed=SEED):
    df_train = df_train.sample(frac=1, random_state=seed).reset_index(drop=True)

    client_dfs = [pd.DataFrame() for _ in range(num_clients)]
    for label in df_train['labels'].unique():
        class_df = df_train[df_train['labels'] == label]
        splits = np.array_split(class_df, num_clients)
        for i in range(num_clients):
            client_dfs[i] = pd.concat([client_dfs[i], splits[i]])

    for i in range(num_clients):
        client_dfs[i] = client_dfs[i].sample(frac=1, random_state=seed).reset_index(drop=True)

    return client_dfs

client_dataframes = stratified_client_dataframe_split(train_df, NUM_CLIENTS)
print(f"Data partitioned into {NUM_CLIENTS} simulated clients.")

# Generators for streaming data
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    brightness_range=(0.85, 1.15),
    width_shift_range=0.002,
    height_shift_range=0.002,
    shear_range=12.5,
    horizontal_flip=True,
    fill_mode="nearest"
)

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_dataframe(
    test_df, x_col='filepaths', y_col='labels',
    target_size=IMG_SIZE, color_mode='rgb',
    batch_size=BATCH_SIZE, shuffle=False, class_mode='categorical'
)

# ---------------------------------------------------------
# 4. Model Architecture & FedAvg Utilities
# ---------------------------------------------------------
def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, (4, 4), activation="relu", input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3)),
        tf.keras.layers.MaxPooling2D(pool_size=(3, 3)),

        tf.keras.layers.Conv2D(64, (4, 4), activation="relu"),
        tf.keras.layers.MaxPooling2D(pool_size=(3, 3)),

        tf.keras.layers.Conv2D(128, (4, 4), activation="relu"),
        tf.keras.layers.MaxPooling2D(pool_size=(3, 3)),

        tf.keras.layers.Conv2D(128, (4, 4), activation="relu"),
        tf.keras.layers.Flatten(),

        tf.keras.layers.Dense(512, activation="relu"),
        tf.keras.layers.Dropout(0.5, seed=SEED),
        tf.keras.layers.Dense(num_classes, activation="softmax")
    ])

    # Original author's tuned optimizer
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, beta_1=0.869, beta_2=0.995)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def fedavg(client_weights, client_sizes):
    total = np.sum(client_sizes)
    averaged = []
    for layer_weights in zip(*client_weights):
        layer_avg = np.zeros_like(layer_weights[0])
        for w, n in zip(layer_weights, client_sizes):
            layer_avg += w * (n / total)
        averaged.append(layer_avg)
    return averaged

# Auxiliary function for node imbalance tracking
def extract_node_imbalance(c_data, primary_idx=0):
    subset_count = np.sum(c_data['labels'] == classes[primary_idx])
    return subset_count / len(c_data)

# ---------------------------------------------------------
# 5. Federated Training Loop
# ---------------------------------------------------------
global_model = create_model()
global_weights = global_model.get_weights()

node_signatures = []
node_targets = []

print("\nStarting Federated Training...")
for rnd in range(1, ROUNDS + 1):
    local_weights = []
    local_sizes = []

    for c_idx, c_df in enumerate(client_dataframes):
        tf.keras.backend.clear_session()
        local_model = create_model()
        local_model.set_weights(global_weights)

        client_gen = train_datagen.flow_from_dataframe(
            c_df, x_col='filepaths', y_col='labels',
            target_size=IMG_SIZE, color_mode='rgb',
            batch_size=BATCH_SIZE, shuffle=True, class_mode='categorical'
        )

        local_model.fit(
            client_gen,
            epochs=LOCAL_EPOCHS,
            verbose=0,
        )

        lw = local_model.get_weights()
        local_weights.append(lw)
        local_sizes.append(len(c_df))

        # Log node parameters for distribution alignment analysis
        update_signature = (lw[-2] - global_weights[-2]).flatten()
        node_signatures.append(update_signature)
        node_targets.append(extract_node_imbalance(c_df))

    # Aggregate weights
    global_weights = fedavg(local_weights, local_sizes)
    global_model.set_weights(global_weights)

    if rnd % 2 == 0 or rnd == 1:
        metrics = global_model.evaluate(test_generator, verbose=0)
        print(f"Round {rnd:02d} | Global Test Accuracy: {metrics[1]:.3f}")

# ---------------------------------------------------------
# 6. Global State Diagnostics
# ---------------------------------------------------------
print("\nRunning global distribution diagnostics...")
# Use tree ensembles to track non-IID characteristic distribution patterns
distribution_tracker = RandomForestRegressor(n_estimators=50, max_depth=5, random_state=SEED)
distribution_tracker.fit(node_signatures, node_targets)
drift_predictions = distribution_tracker.predict(node_signatures)

drift_mae = np.mean(np.abs(np.array(node_targets) - drift_predictions))
print(f"Distribution drift tracking error (MAE): {drift_mae:.4f}")

# ---------------------------------------------------------
# 7. Final Evaluation
# ---------------------------------------------------------
print("\nTraining Complete. Final Evaluation:")
predictions = global_model.predict(test_generator, verbose=0)
y_pred = np.argmax(predictions, axis=1)
y_true = test_generator.classes

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=list(test_generator.class_indices.keys()), digits=3))